import React from 'react'
import { Table } from "reactstrap";

export default function Jeemainmathtb() {
    return (
       <div>
         <Table hover className="accortable">
            <tbody>
            <tr><td className= "tbl-cell-border1"><p><strong>S.No.</strong></p></td><td className= "tbl-cell-border1"><p><strong>Units</strong></p></td><td className= "tbl-cell-border1"><p><strong>Topics</strong></p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>1</p></td><td className= "tbl-cell-border1"><p>Sets, Relations and Functions</p></td><td className= "tbl-cell-border1"><p>Sets and their representation; Union, intersection and complement of sets and their algebraic properties; Power set; Relation, Types of relations, equivalence relations, functions;, one-one, into and onto functions, composition of functions,</p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>2</p></td><td className= "tbl-cell-border1"><p>Complex Numbers and Quadratic Equations</p></td><td className= "tbl-cell-border1"><p>Complex numbers as ordered pairs of reals, Representation of complex numbers in the form a+ib and their representation in a plane, Argand diagram, algebra of complex numbers, modulus and argument (or amplitude) of a complex number, square root of a complex number, triangle inequality, Quadratic equations in real and complex number system and their solutions. Relation between roots and co-efficients, nature of roots, formation of quadratic equations with given roots.</p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>3</p></td><td className= "tbl-cell-border1"><p>Matrices and Determinants</p></td><td className= "tbl-cell-border1"><p>Matrices, algebra of matrices, types of matrices, determinants and matrices of order two and three. Properties of determinants, evaluation of determinants, area of triangles using determinants. Adjoint and evaluation of inverse of a square matrix using determinants and elementary transformations, Test of consistency and solution of simultaneous linear equations in two or three variables using determinants and matrices.</p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>4</p></td><td className= "tbl-cell-border1"><p>Permutations And Combinations</p></td><td className= "tbl-cell-border1"><p>Fundamental principle of counting, permutation as an arrangement and combination as selection, Meaning of P (n,r) and C (n,r), simple applications.</p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>5</p></td><td className= "tbl-cell-border1"><p>Mathematical Induction</p></td><td className= "tbl-cell-border1"><p>Principle of Mathematical Induction and its simple applications.</p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>6</p></td><td className= "tbl-cell-border1"><p>Binomial Theorem and its Simple Applications</p></td><td className= "tbl-cell-border1"><p>Binomial theorem for a positive integral index, general term and middle term, properties of Binomial coefficients and simple applications.</p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>7</p></td><td className= "tbl-cell-border1"><p>Sequences and Series</p></td><td className= "tbl-cell-border1"><p>Arithmetic and Geometric progressions, insertion of arithmetic, geometric means between two given numbers. Relation between A.M. and G.M. Sum upto n terms of special series: S n, S n2, Sn3. Arithmetico-Geometric progression.</p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>8</p></td><td className= "tbl-cell-border1"><p>Limit, Continuity and Differentiability</p></td><td className= "tbl-cell-border1"><p>Real - valued functions, algebra of functions, polynomials, rational, trigonometric, logarithmic and exponential functions, inverse functions. Graphs of simple functions. Limits, continuity and differentiability. Differentiation of the sum, difference, product and quotient of two functions. Differentiation of trigonometric, inverse trigonometric, logarithmic, exponential, composite and implicit functions; derivatives of order upto two. Rolle&apos;s and Lagrange&apos;s Mean Value Theorems. Applications of derivatives: Rate of change of quantities, monotonic - increasing and decreasing functions, Maxima and minima of functions of one variable, tangents and normals.</p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>9</p></td><td className= "tbl-cell-border1"><p>Integral Calculus</p></td><td className= "tbl-cell-border1"><p>Integral as an anti - derivative. Fundamental integrals involving algebraic, trigonometric, exponential and logarithmic functions. Integration by substitution, by parts and by partial fractions. Integration using trigonometric identities.</p><p>Integral as limit of a sum. Fundamental Theorem of Calculus. Properties of definite integrals. Evaluation of definite integrals, determining areas of the regions bounded by simple curves in standard form.</p><div data-empty="true"><br/></div></td></tr>
            <tr><td className= "tbl-cell-border1"><p>10</p></td><td className= "tbl-cell-border1"><p>Differential Equations</p></td><td className= "tbl-cell-border1"><p>Ordinary differential equations, their order and degree. Formation of differential equations. Solution of differential equations by the method of separation of variables, solution of homogeneous and linear differential equations.</p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>11</p></td><td className= "tbl-cell-border1"><p>Co-ordinate Geometry</p></td><td className= "tbl-cell-border1"><p>Cartesian system of rectangular co-ordinates 10 in a plane, distance formula, section formula, locus and its equation, translation of axes, slope of a line, parallel and perpendicular lines, intercepts of a line on the coordinate axes.</p><p>Straight lines</p><p>Various forms of equations of a line, intersection of lines, angles between two lines, conditions for concurrence of three lines, distance of a point from a line, equations of internal and external bisectors of angles between two lines, coordinates of centroid, orthocentre and circumcentre of a triangle, equation of family of lines passing through the point of intersection of two lines.</p><p>Circles, conic sections</p><p>Standard form of equation of a circle, general form of the equation of a circle, its radius and centre, equation of a circle when the end points of a diameter are given, points of intersection of a line and a circle with the centre at the origin and condition for a line to be tangent to a circle, equation of the tangent. Sections of cones, equations of conic sections (parabola, ellipse and hyperbola) in standard forms, condition for y = mx + c to be a tangent and point (s) of tangency.</p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>12</p></td><td className= "tbl-cell-border1"><p>Three Dimensional Geometry</p></td><td className= "tbl-cell-border1"><p>Coordinates of a point in space, distance between two points, section formula, direction ratios and direction cosines, angle between two intersecting lines. Skew lines, the shortest distance between them and its equation. Equations of a line and a plane in different forms, intersection of a line and a plane, coplanar lines.</p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>13</p></td><td className= "tbl-cell-border1"><p>Vector Algebra</p></td><td className= "tbl-cell-border1"><p>Vectors and scalars, addition of vectors, components of a vector in two dimensions and three-dimensional space, scalar and vector products, scalar and vector triple product.</p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>14</p></td><td className= "tbl-cell-border1"><p>Statistics and Probability</p></td><td className= "tbl-cell-border1"><p>Measures of Dispersion: Calculation of mean, median, mode of grouped and ungrouped data calculation of standard deviation, variance and mean deviation for grouped and ungrouped data.</p><p>Probability: Probability of an event, addition and multiplication theorems of probability, Baye&apos;s theorem, probability distribution of a random variate, Bernoulli trials and Binomial distribution.</p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>15</p></td><td className= "tbl-cell-border1"><p>Trigonometry</p></td><td className= "tbl-cell-border1"><p>Trigonometrical identities and equations. Trigonometrical functions. Inverse trigonometrical functions and their properties. Heights and Distances</p></td></tr>
            <tr><td className= "tbl-cell-border1"><p>16</p></td><td className= "tbl-cell-border1"><p>Mathematical Reasoning</p></td><td className= "tbl-cell-border1"><p>Statements, logical operations and, or, implies, implied by, if and only if. Understanding of tautology, contradiction, converse and contrapositive.</p></td></tr>
            </tbody>
            </Table>
    </div>
    )
}
