import React from 'react'
import { Table } from "reactstrap";

export default function Jeemainchemtb() {
    return (
        <div>
            <Table hover className="accortable">
            <tbody>
            <tr><td><p><strong>S.No</strong></p></td><td><p><strong>Units</strong></p></td><td><p><strong>Chemistry Topics</strong></p></td></tr>
            <tr><td colSpan="3"><h5 className="text-danger"><strong>IIT JEE Main Physical Chemistry Syllabus 2022 (Section A)</strong></h5></td></tr>
            <tr><td><p>1</p></td><td><p>Some Basic Concepts in Chemistry</p></td><td><p>Matter and its nature, Dalton&apos;s atomic theory; Concept of atom, molecule, element and compound; Physical quantities and their measurements in Chemistry, precision and accuracy, significant figures, S.I. Units, dimensional analysis; Laws of chemical combination: Atomic and molecular masses, mole concept, molar mass, percentage composition, empirical and molecular formulae; Chemical equations and stoichiometry.</p></td></tr>
            <tr><td><p>2</p></td><td><p>States of Matter</p></td><td><p>Classification of matter into solid, liquid and gaseous states.</p><p><strong>Gaseous State:- </strong>Measurable properties of gases; Gas laws - Boyle&apos;s law, Charle&apos;s law, Graham&apos;s law of diffusion, Avogadro&apos;s law, Dalton&apos;s law of partial pressure; Concept of Absolute scale of temperature; Ideal gas equation; Kinetic theory of gases (only postulates); Concept of average, root mean square and most probable velocities; Real gases, deviation from Ideal behaviour, compressibility factor and van der Waals equation.</p><p><strong>Liquid State:-</strong> Properties of liquids - vapour pressure, viscosity and surface tension and effect of temperature on them (qualitative treatment only).</p><p><strong>Solid State:- </strong>Classification of solids: molecular, ionic, covalent and metallic solids, amorphous and crystalline solids (elementary idea); Bragg&apos;s Law and its applications; Unit cell and lattices, packing in solids (fee, bec and hep lattices), voids, calculations involving unit cell parameters, imperfection in solids; Electrical and magnetic properties.</p></td></tr>
            <tr><td><p>3</p></td><td><p>Atomic Structure</p></td><td><p>Thomson and Rutherford atomic models and their limitations; Nature of electromagnetic radiation, photoelectric effect; Spectrum of hydrogen atom, Bohr model of hydrogen atom - its postulates, derivation of the relations for energy of the electron and radii of the different orbits, limitations of Bohr&apos;s model; Dual nature of matter, de-Broglie&apos;s relationship, Heisenberg uncertainty principle. Elementary ideas of quantum mechanics, quantum mechanical model of atom, its important features. Concept of atomic orbitals as one electron wave functions; Variation of t|/ and \|/2 with r for Is and 2s orbitals; various quantum numbers (principal, angular momentum and magnetic quantum numbers) and their significance; shapes of s, p and d - orbitals, electron spin and spin quantum number; Rules for filling electrons in orbitals - aufbau principle, Pauli&apos;s exclusion principle and Hund&apos;s rule, electronic configuration of elements, extra stability of half-filled and completely filled orbitals.</p></td></tr>
            <tr><td><p>4</p></td><td><p>Chemical Bonding and Molecular Structure</p></td><td><p>Kossel - Lewis approach to chemical bond formation, concept of ionic and covalent bonds.</p><p>Ionic Bonding: Formation of ionic bonds, factors affecting the formation of ionic bonds; calculation of lattice enthalpy.</p><p>Covalent Bonding: Concept of electronegativity, Fajan&apos;s rule, dipole moment; Valence Shell Electron Pair Repulsion (VSEPR) theory and shapes of simple molecules.</p><p>Quantum mechanical approach to covalent bonding:</p><p>Valence bond theory - Its important features, concept of hybridization involving s, p and d orbitals; Resonance.</p><p>Molecular Orbital Theory - Its important features, LCAOs, types of molecular orbitals (bonding, antibonding), sigma and pi-bonds, molecular orbital electronic configurations of homonuclear diatomic molecules, concept of bond order, bond length and bond energy.</p><p>Elementary idea of metallic bonding. Hydrogen bonding and its applications.</p></td></tr>
            <tr><td><p>5</p></td><td><p>Chemical Thermodynamics</p></td><td><p>Fundamentals of thermodynamics: System and surroundings, extensive and intensive properties, state functions, types of processes.</p><p>First law of thermodynamics - Concept of work, heat internal energy and enthalpy, heat capacity, molar heat capacity; Hess&apos;s law of constant heat summation; Enthalpies of bond dissociation, combustion, formation, atomization, sublimation, phase transition, hydration, ionization and solution.</p><p>Second law of thermodynamics: Spontaneity of processes; AS of the universe and AG of the system as criteria for spontaneity, AG (Standard Gibbs energy change) and equilibrium constant.</p></td></tr>
            <tr><td><p>6</p></td><td><p>Solutions</p></td><td><p>Different methods for expressing concentration of solution - molality, molarity, mole fraction, percentage (by volume and mass both), vapour pressure of solutions and Raoult&apos;s Law - Ideal and non-ideal solutions, vapour pressure - composition, plots for ideal and non-ideal solutions; Colligative properties of dilute solutions - relative lowering of vapour pressure, depression of freezing point, elevation of boiling point and osmotic pressure; Determination of molecular mass using colligative properties; Abnormal value of molar mass, van&apos;t Hoff factor and its significance.</p></td></tr>
            <tr><td><p>7</p></td><td><p>Equilibrium</p></td><td><p>Meaning of equilibrium, concept of dynamic equilibrium.</p><p>Equilibria involving physical processes: Solid -liquid, liquid - gas and solid - gas equilibria, Henry&apos;s law, general characteristics of equilibrium involving physical processes.</p><p>Equilibria involving chemical processes: Law of</p><p>chemical equilibrium, equilibrium constants (Kp and Kc) and their significance, significance of AG and AG in chemical equilibria, factors affecting equilibrium concentration, pressure, temperature, effect of catalyst; Le Chatelier&apos;s principle.</p><p>Ionic equilibrium: Weak and strong electrolytes, ionization of electrolytes, various concepts of acids and bases (Arrhenius, Bronsted - Lowry and Lewis) and their ionization, acid - base equilibria (including multistage ionization) and ionization constants, ionization of water, pH scale, common ion effect, hydrolysis of salts and pH of their solutions, solubility of sparingly soluble salts and solubility products, buffer solutions.</p></td></tr>
            <tr><td><p>8</p></td><td><p>Redox Reactions and Electro-chemistry</p></td><td><p>Electronic concepts of oxidation and reduction, redox reactions, oxidation number, rules for assigning oxidation number, balancing of redox reactions.</p><p>Electrolytic and metallic conduction, conductance in electrolytic solutions, molar conductivities and their variation with concentration: Kohlrausch&apos;s law and its applications.</p><p>Electrochemical cells - Electrolytic and Galvanic cells, different types of electrodes, electrode potentials including standard electrode potential, half - cell and cell reactions, emf of a Galvanic cell and its measurement; Nernst equation and its applications; Relationship between cell potential and Gibbs&apos; energy change; Dry cell and lead accumulator; Fuel cells.</p></td></tr>
            <tr><td><p>9</p></td><td><p>Chemical Kinetics</p></td><td><p>Rate of a chemical reaction, factors affecting the rate of reactions: concentration, temperature, pressure and catalyst; elementary and complex reactions, order and molecularity of reactions, rate law, rate constant and its units, differential and integral forms of zero and first order reactions, their characteristics and half -lives, effect of temperature on the rate of reactions -Arrhenius theory, activation energy and its calculation, collision theory of bimolecular gaseous reactions (no derivation).</p></td></tr>
            <tr><td><p>10</p></td><td><p>Surface Chemistry</p></td><td><p>Adsorption- Physisorption and chemisorption and their characteristics, factors affecting adsorption of gases on solids - Freundlich and Langmuir adsorption isotherms, adsorption from solutions.</p><p>Catalysis - Homogeneous and heterogeneous, activity and selectivity of solid catalysts, enzyme catalysis and its mechanism.</p><p>Colloidal state- distinction among true solutions, colloids and suspensions, classification of colloids -lyophilic, lyophobic; multimolecular, macromolecular and associated colloids (micelles), preparation and properties of colloids - Tyndall effect, Brownian movement, electrophoresis, dialysis, coagulation and flocculation; Emulsions and their characteristics.</p></td></tr>
            <tr><td colSpan="3"><h5 className="text-danger"><strong>IIT JEE Main Inorganic Chemistry Syllabus 2022</strong></h5></td></tr>
            <tr><td><p>11</p></td><td><p>Classification of Elements and Periodicity in Properties</p></td><td><p>Modem periodic law and present form of the periodic table, s, p, d and f block elements, periodic trends in properties of elements atomic and ionic radii, ionization enthalpy, electron gain enthalpy, valence, oxidation states and chemical reactivity.</p></td></tr>
            <tr><td><p>12</p></td><td><p> General Principles and Processes of Isolation of Metals</p></td><td><p>Modes of occurrence of elements in nature, minerals, ores; Steps involved in the extraction of metals -concentration, reduction (chemical and electrolytic methods) and refining with special reference to the extraction of Al, Cu, Zn and Fe; Thermodynamic and electrochemical principles involved in the extraction of metals.</p></td></tr>
            <tr><td><p>13</p></td><td><p>ydrogen</p></td><td><p>Position of hydrogen in periodic table, isotopes, preparation, properties and uses of hydrogen; Physical and chemical properties of water and heavy water; Structure, preparation, reactions and uses of hydrogen peroxide; Classification of hydrides - ionic, covalent and interstitial; Hydrogen as a fuel.</p></td></tr>
            <tr><td><p>14</p></td><td><p>S - Block Elements (Alkali and Alkaline Earth Metals)</p></td><td><p><strong>Group -1 and 2 Elements-</strong> General introduction, electronic configuration and general trends in physical and chemical properties of elements, anomalous properties of the first element of each group, diagonal relationships.</p><p>Preparation and properties of some important compounds - sodium carbonate and sodium hydroxide and sodium hydrogen carbonate; Industrial uses of lime, limestone, Plaster of Paris and cement; Biological significance of Na, K, Mg and Ca.</p></td></tr>
            <tr><td><p>15</p></td><td><p>p- Block Elements</p></td><td><ul><li><strong>Group -13 to Group 18 Elements</strong>- General Introduction: Electronic configurations and general trends in physical and chemical properties of elements across the periods and down the groups; unique behaviour of the first element in each group.</li><li><strong>Groupwise study of the p - block elements Group -13</strong>- Preparation, properties and uses of boron and aluminium; Structure, properties and uses of borax, boric acid, diborane, boron trifluoride, aluminium chloride and alums.</li><li><strong>Group -14-</strong> Tendency for catenation; Structure, properties and uses of Allotropes and oxides of carbon, silicon tetrachloride, silicates, zeolites and silicones.</li><li><strong>Group -15</strong>- Properties and uses of nitrogen and phosphorus; Allotropic forms of phosphorus; Preparation, properties, structure and uses of ammonia, nitric acid, phosphine and phosphorus halides, (PC13, PCI,); Structures of oxides and oxoacids of nitrogen and phosphorus.</li><li><strong>Group -16</strong> Preparation, properties, structures and uses of ozone; Allotropic forms of sulphur; Preparation, properties, structures and uses of sulphuric acid (including its industrial preparation); Structures of oxoacids of sulphur.</li><li><strong>Group -17</strong>- Preparation, properties and uses of hydrochloric acid; Trends in the acidic nature of hydrogen halides; Structures of Interhalogen compounds and oxides and oxoacids of halogens.</li><li><strong>Group-18- </strong>Occurrence and uses of noble gases; Structures of fluorides and oxides of xenon.</li></ul></td></tr>
            <tr><td><p>16</p></td><td><p>d - and f - Block Elements</p></td><td><p><strong>Transition Elements- </strong>General introduction, electronic configuration, occurrence and characteristics, general trends in properties of the first row transition elements -physical properties, ionization enthalpy, oxidation states, atomic radii, colour, catalytic behaviour, magnetic properties, complex formation, interstitial compounds, alloy formation; Preparation, properties and uses of K2 Cr, 07 and Kmn04.</p><p>Inner Transition Elements</p><p>Lanthanoids - Electronic configuration, oxidation states and lanthanide contraction.</p><p>Actinides - Electronic configuration and oxidation states.</p></td></tr>
            <tr><td><p>17</p></td><td><p>Co-Ordination Compounds</p></td><td><p>Introduction to co-ordination compounds, Werner&apos;s theory; ligands, co-ordination number, denticity, chelation; IUPAC nomenclature of mononuclear coordination compounds, isomerism; Bonding-Valence bond approach and basic ideas of Crystal field theory, colour and magnetic properties; Importance of co­ordination compounds (in qualitative analysis, extraction of metals and in biological systems).</p></td></tr>
            <tr><td><p>18</p></td><td><p>Environmental Chemistry</p></td><td><ul><li>Environmental pollution - Atmospheric, water and soil.</li><li>Atmospheric pollution - Tropospheric and Stratospheric</li><li>Tropospheric pollutants - Gaseous pollutants: Oxides of carbon, nitrogen and sulphur, hydrocarbons; their sources, harmful effects and prevention; Green house effect and Global warming; Acid rain;</li><li>Particulate pollutants: Smoke, dust, smog, fumes, mist; their sources, harmful effects and prevention.</li><li>Stratospheric pollution- Formation and breakdown of ozone, depletion of ozone layer - its mechanism and effects.</li><li>Water Pollution - Major pollutants such as, pathogens, organic wastes and chemical pollutants; their harmful effects and prevention.</li><li>Soil pollution - Major pollutants such as: Pesticides (insecticides, herbicides and fungicides), their harmful effects and prevention.</li><li>Strategies to control environmental pollution.</li></ul></td></tr>
            <tr><td colSpan="3"><h5 className="text-danger"><strong>IIT JEE Main Organic Chemistry Syllabus 2022 -Section C</strong></h5></td></tr>
            <tr><td><p>19</p></td><td><p>Purification and Characterization of Organic Compounds</p></td><td><ul><li>Purification - Crystallization, sublimation, distillation, differential extraction and chromatography - principles and their applications.</li><li>Qualitative analysis - Detection of nitrogen, sulphur, phosphorus and halogens.</li><li>Quantitative analysis (basic principles only)- Estimation of carbon, hydrogen, nitrogen, halogens, sulphur, phosphorus.</li><li>Calculations of empirical formulae and molecular formulae; Numerical problems in organic quantitative analysis.</li></ul></td></tr>
            <tr><td><p>20</p></td><td><p>Some Basic Principles of Organic Chemistry</p></td><td><p>Tetravalency of carbon; Shapes of simple molecules -hybridization (s and p); Classification of organic compounds based on functional groups: and those containing halogens, oxygen, nitrogen and sulphur; Homologous series; Isomerism - structural and stereoisomerism.</p><p>Nomenclature (Trivial and IUPAC)- Covalent bond fission - Homolytic and heterolytic: free radicals, carbocations and carbanions; stability of carbocations and free radicals, electrophiles and nucleophiles.</p><p>Electronic displacement in a covalent bond</p><p>- Inductive effect, electromeric effect, resonance and hyperconjugation.</p><div data-empty="true"><br/></div><p>Common types of organic reactions- Substitution, addition, elimination and rearrangement.</p></td></tr>
            <tr><td><p>21</p></td><td><p>Hydrocarbons</p></td><td><p>Classification, isomerism, IUPAC nomenclature, general methods of preparation, properties and reactions.</p><div data-empty="true"><br/></div><p>Alkanes - Conformations: Sawhorse and Newman projections (of ethane); Mechanism of halogenation of alkanes.</p><p>Alkenes - Geometrical isomerism; Mechanism of electrophilic addition: addition of hydrogen, halogens, water, hydrogen halides (Markownikoff s and peroxide effect); Ozonolysis and polymerization.</p><p>Alkynes - Acidic character; Addition of hydrogen, halogens, water and hydrogen halides; Polymerization.</p><p>Aromatic hydrocarbons - Nomenclature, benzene -structure and aromaticity; Mechanism of electrophilic substitution: halogenation, nitration, Friedel - Craft&apos;s alkylation and acylation, directive influence of functional group in mono-substituted benzene.</p></td></tr>
            <tr><td><p>22</p></td><td><p>Organic Compounds Containing Halogens</p></td><td><p>General methods of preparation, properties and reactions; Nature of C-X bond; Mechanisms of substitution reactions.</p><p>Uses; Environmental effects of chloroform, iodoform freons and DDT.</p></td></tr>
            <tr><td><p>23</p></td><td><p>Organic Compounds Containing Oxygen</p></td><td><p>General methods of preparation, properties, reactions and uses.</p><p>ALCOHOLS, PHENOLS AND ETHERS</p><ul><li>Alcohols: Identification of primary, secondary and tertiary alcohols; mechanism of dehydration.</li><li>Phenols: Acidic nature, electrophilic substitution reactions: halogenation, nitration and sulphonation, Reitner - Tiemann reaction.</li><li>Ethers: Structure.</li><li>Aldehyde and Ketones: Nature of carbonyl group;Nucleophilic addition to &gt;C=0 group, relative reactivities of aldehydes and ketones; Important reactions such as - Nucleophilic addition reactions (addition of HCN, NH, and its derivatives), Grignard reagent; oxidation; reduction (Wolff Kishner and Clemmensen); acidity of a-hydrogen, aldol condensation, Cannizzaro reaction, Haloform reaction;</li><li>Chemical tests to distinguish between aldehydes and Ketones.</li><li>Carboxylic Acids- Acidic strength and factors affecting it.</li></ul></td></tr>
            <tr><td><p>24</p></td><td><p>Organic Compounds Containing Nitrogen</p></td><td><ul><li>General methods of preparation, properties, reactions and uses.</li><li>Amines: Nomenclature, classification, structure, basic character and identification of primary, secondary and tertiary amines and their basic character.</li><li>Diazonium Salts: Importance in synthetic organic chemistry.</li></ul></td></tr>
            <tr><td><p>25</p></td><td><p>olymers</p></td><td><p>General introduction and classification of polymers, general methods of polymerization-addition and condensation, copolymerization;</p><p>Natural and synthetic rubber and vulcanization; some important polymers with emphasis on their monomers and uses - polythene, nylon, polyester and bakelite.</p></td></tr>
            <tr><td><p>26</p></td><td><p>Biomolecules</p></td><td><p>General introduction and importance of biomolecules.</p><ul><li>Carbohydrates - Classification: aldoses and ketoses; monosaccharides (glucose and fructose) and constituent monosaccharides of oligosaccharides (sucrose, lactose and maltose).</li><li>Proteins - Elementary Idea of a-amino acids, peptide bond, polypeptides; Proteins: primary, secondary, tertiary and quaternary structure (qualitative idea only), denaturation of proteins, enzymes.</li><li>Vitamins - Classification and functions.</li><li>Nucleic Acids - Chemical constitution of DNA and RNA.</li><li>Biological functions of nucleic acids.</li></ul></td></tr>
            <tr><td><p>27</p></td><td><p>Chemistry In Everyday Life</p></td><td><ul><li>Chemicals in medicines - Analgesics, tranquilizers, antiseptics, disinfectants, antimicrobials, antifertility drugs, antibiotics, antacids, antihistamine - their meaning and common examples.</li><li>Chemicals in food - Preservatives, artificial sweetening agents - common examples.</li><li>Cleansing agents - Soaps and detergents, cleansing action.</li></ul></td></tr>
            <tr><td><p>28</p></td><td><p>Principles Related to Practical Chemistry</p></td><td><p>Detection of extra elements (N,S, halogens) in organic compounds; Detection of the following functional groups: hydroxyl (alcoholic and phenolic), carbonyl (aldehyde and ketone), carboxyl and amino groups in organic compounds.</p><p>• Chemistry involved in the preparation of the following:</p><p>Inorganic compounds: Mohr&apos;s salt, potash alum. Organic compounds: Acetanilide, p nitroacetanilide, aniline yellow, iodoform.</p><p>•Chemistry involved in the titrimetric exercises -Acids bases and the use of indicators, oxalic-acid vs KMnO,, Mohr&apos;s salt vs KMnO,.</p><p>•Chemical principles involved in the qualitative salt analysis:</p><p>Cations - Pb2+, Cu!+, Af,+, Fe1+, Zn2+, Ni2+, Ca2+, Ba2+,</p><p>Mg2+, nh;.</p><p>Anions- CO, S2~, SO4, NO, NO~2, Cf, Br, I . (Insoluble salts excluded).</p><p>•Chemical principles involved in the following experiments:</p><p>1. Enthalpy of solution of CuS04</p><p>2. Enthalpy of neutralization of strong acid and strong base.</p><p>3. Preparation of lyophilic and lyophobic sols.</p><p>4. Kinetic study of reaction of iodide ion with hydrogen peroxide at room temperature.</p></td></tr>

          </tbody>

            </Table>
        </div>
    )
}
