import React from "react";
import { Table } from "reactstrap";

export default function NeetphyTable() {
  return (
    <div>
        <h5 className="text-danger"> NEET Physics Syllabus 2022 Highlights - </h5>
        <Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <td>Total weightage</td> <td>25% of NEET Syllabus&nbsp;</td> </tr> <tr> <td>Number of questions asked</td> <td>Section A: 35, Section B: 15 (attempt only 10 from sec B)</td> </tr> <tr> <td>Marks allotted for each question</td> <td>4 marks for correct answer</td> </tr> <tr> <td>Negative marking</td> <td>1 marks will be reduced for wrong answer</td> </tr> <tr> <td>Total marks for Physics</td> <td>180 out of 720 marks</td> </tr> </tbody> </Table>
        <h5 className="text-danger">NEET Physics Syllabus from Class 11</h5>
Unit 1

<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Physical World and Measurement</td> <td> <ul> <li>Physics: Scope and excitement; nature of physical laws; Physics, technology, and society.</li> <li>Need for measurement: Units of measurement; systems of units; SI units, fundamental and derived units. Length, mass, and time measurements; accuracy and precision of measuring instruments; errors in measurement; significant figures.</li> <li>Dimensions of physical quantities, dimensional analysis, and its applications.</li> </ul> </td> </tr> </tbody> </Table>
Unit 2
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Kinematics</td> <td> <ul> <li>A frame of reference, Motion in a straight line; Position-time graph, speed, and velocity. Uniform and non-uniform motion, average speed, and instantaneous velocity. Uniformly accelerated motion, velocity-time, and position-time graphs, for uniformly accelerated motion (graphical treatment).</li> <li>Elementary concepts of differentiation and integration for describing motion. Scalar and vector quantities: Position and displacement vectors, general vectors, general vectors and notation, equality of vectors, multiplication of vectors by a real number; addition and subtraction of vectors. Relative velocity.</li> <li>Unit vectors. Resolution of a vector in a plane-rectangular component.</li> <li>Scalar and Vector products of Vectors. Motion in a plane. Cases of uniform velocity and uniform acceleration- projectile motion. Uniform circular motion.</li> </ul> </td> </tr> </tbody> </Table>  
Unit 3 
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Laws of Motion</td> <td> <ul> <li>Intuitive concept of force. Inertia, Newton’s first law of motion; momentum and Newton’s second law of motion; impulse; Newton’s third law of motion. Law of conservation of linear momentum and its applications.</li> <li>Equilibrium of concurrent forces. Static and Kinetic friction, laws of friction, rolling friction, lubrication. 69</li> <li>Dynamics of uniform circular motion. Centripetal force, examples of circular motion (vehicle on level circular road, vehicle on banked road).</li> </ul> </td> </tr> </tbody> </Table>
Unit 4
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Work, Energy, and Power</td> <td> <p className="accortable js-invalid-para">Work done by a constant force and variable force; kinetic energy, work-energy theorem, power.</p> <p className="accortable js-invalid-para">Notion of potential energy, the potential energy of a spring, conservative forces; conservation of mechanical energy (kinetic and potential energies); nonconservative forces; motion in a vertical circle, elastic and inelastic collisions in one and two dimensions.</p> </td> </tr> </tbody> </Table>
Unit 5
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Motion of System of Particles and Rigid Body</td> <td> <ul> <li>Centre of mass of a two-particle system, momentum conservation, and centre of mass motion. Centre of mass of a rigid body; centre of mass of uniform rod.</li> <li>Moment of a force,-torque, angular momentum, conservation of angular momentum with some examples.</li> <li>Equilibrium of rigid bodies, rigid body rotation, and equation of rotational motion, comparison of linear and rotational motions; the moment of inertia, the radius of gyration. Values of M.I. for simple geometrical objects (no derivation). Statement of parallel and perpendicular axes theorems and their applications.</li> </ul> </td> </tr> </tbody> </Table>
Unit 6
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Gravitation</td> <td> <ul> <li>Kepler’s laws of planetary motion. The universal law of gravitation. Acceleration due to gravity and its variation with altitude and depth.</li> <li>Gravitational potential energy; gravitational potential. Escape velocity, orbital velocity of a satellite. Geostationary satellites.</li> </ul> </td> </tr> </tbody> </Table>
Unit 7
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Properties of Bulk Matter</td> <td> <ul> <li>Elastic behavior, Stress-strain relationship. Hooke’s law, Young’s modulus, bulk modulus, shear, modulus of rigidity, poisson’s ratio; elastic energy.</li> <li>Viscosity, Stokes’ law, terminal velocity, Reynold’s number, streamline and turbulent flow. Critical velocity, Bernoulli’s theorem and its applications.</li> <li>Surface energy and surface tension, angle of contact, excess of pressure, application of surface tension ideas to drops, bubbles and capillary rise.&nbsp;</li> <li>Heat, temperature, thermal expansion; thermal expansion of solids, liquids, and gases. Anomalous expansion. Specific heat capacity: Cp, Cv- calorimetry; change of state – latent heat.</li> <li>Heat transfer- conduction and thermal conductivity, convection and radiation. Qualitative ideas of Black Body Radiation, Wein’s displacement law, and Green House effect.</li> <li>Newton’s law of cooling and Stefan’s law</li> </ul> </td> </tr> </tbody> </Table>
Unit 8
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Thermodynamics</td> <td> <ul> <li>Thermal equilibrium and definition of temperature (zeroth law of Thermodynamics). Heat, work and internal energy. First law of thermodynamics. Isothermal and adiabatic processes.</li> <li>Second law of the thermodynamics: Reversible and irreversible processes. Heat engines and refrigerators.</li> </ul> </td> </tr> </tbody> </Table>
Unit 9
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Behaviour of Perfect Gas and Kinetic Theory</td> <td> <ul> <li>Equation of state of a perfect gas, work done on compressing a gas.</li> <li>Kinetic theory of gases: Assumptions, concept of pressure. Kinetic energy and temperature; degrees of freedom, law of equipartition of energy (statement only) and application to specific heat capacities of gases; concept of mean free path.</li> </ul> </td> </tr> </tbody> </Table>
Unit 10
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Oscillations and Waves</td> <td> <ul> <li>Periodic motion-period, frequency, displacement as a function of time. Periodic functions. Simple harmonic motion(SHM) and its equation; phase; oscillations of a spring-restoring force and force constant; energy in SHM –Kinetic and potential energies; simple pendulum-derivation of expression for its time period; free, forced and damped oscillations (qualitative ideas only), resonance.</li> <li>Wave motion. Longitudinal and transverse waves, speed of wave motion. Displacement relation for a progressive wave. Principle of superposition of waves, reflection of waves, standing waves in strings and organ pipes, fundamental mode and harmonics. Beats. Doppler effect.</li> </ul> </td> </tr> </tbody> </Table>


<h5 className="text-danger">NEET Physics Syllabus from Class 12</h5>
Unit 1
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Electrostatics</td> <td> <ul> <li>Electric charges and their conservation. Coulomb’s law-force between two point charges, forces between multiple charges; superposition principle and continuous charge distribution.</li> <li>Electric field, electric field due to a point charge, electric field lines; electric dipole, electric field due to a dipole; torque on a dipole in a uniform electric field.</li> <li>Electric flux, statement of Gauss’s theorem and its applications to find field due to infinitely long straight wire, uniformly charged infinite plane sheet and uniformly charged thin spherical shell (field inside and outside)</li> <li>Electric potential, potential difference, electric potential due to a point charge, a dipole and system of charges: equipotential surfaces, electrical potential energy of a system of two point charges and of electric diploes in an electrostatic field.</li> <li>Conductors and insulators, free charges and bound charges inside a conductor. Dielectrics and electric polarization, capacitors and capacitance, combination of capacitors in series and in parallel, capacitance of a parallel plate capacitor with and without dielectric medium between the plates, energy stored in a capacitor, Van de Graaff generator.</li> </ul> </td> </tr> </tbody> </Table>
Unit 2
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Current Electricity</td> <td> <ul> <li>Electric current, the flow of electric charges in a metallic conductor, drift velocity and mobility, and their relation with electric current; Ohm’s law, electrical resistance, V-I characteristics (liner and nonlinear), electrical energy and power, electrical resistivity, and conductivity.</li> <li>Carbon resistors, color code for carbon resistors; series and parallel combinations of resistors; temperature dependence of resistance.</li> <li>Internal resistance of a cell, potential difference and emf of a cell, combination of cells in series and in parallel.</li> <li>Kirchhoff’s laws and simple applications. Wheatstone bridge, metre bridge.</li> <li>Potentiometer-principle and applications to measure potential difference, and for comparing emf of two cells; measurement of internal resistance of a cell.</li> </ul> </td> </tr> </tbody> </Table>
Unit 3
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Magnetic Effects of Current and Magnetism</td> <td> <ul> <li>Concept of magnetic field, Oersted’s experiment. Biot-Savart law and its application to current carrying circular loop.</li> <li>Ampere’s law and its applications to infinitely long straight wire, straight and toroidal solenoids. Force on a moving charge in uniform magnetic and electric fields. Cyclotron.</li> <li>Force on a current-carrying conductor in a uniform magnetic field. Force between two parallel current-carrying conductors-definition of ampere. Torque experienced by a current loop in a magnetic field; moving coil galvanometer-its current sensitivity and conversion to ammeter and voltmeter.</li> <li>Current loop as a magnetic dipole and its magnetic dipole moment. Magnetic dipole moment of a revolving electron. Magnetic field intensity due to a magnetic dipole (bar magnet) along its axis and perpendicular to its axis. Torque on a magnetic dipole (bar magnet) in a uniform magnetic field; bar magnet as an equivalent solenoid, magnetic field lines; Earth’s magnetic field and magnetic elements.</li> <li>Para-, dia-and ferro-magnetic substances, with examples.</li> <li>Electromagnetic and factors affecting their strengths. Permanent magnets.</li> </ul> </td> </tr> </tbody> </Table>
Unit 4
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Electromagnetic Induction and Alternating Currents</td> <td> <ul> <li>Electromagnetic induction; Faraday’s law, induced emf and current; Lenz’s Law, Eddy currents. Self and mutual inductance.</li> <li>Alternating currents, peak and rms value of alternating current/ voltage; reactance and impedance; LC oscillations (qualitative treatment only), LCR series circuit, resonance; power in AC circuits, wattles current.</li> <li>AC generator and transformer.</li> </ul> </td> </tr> </tbody> </Table>
Unit 5
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Electromagnetic Waves</td> <td> <ul> <li>Need for displacement current.</li> <li>Electromagnetic waves and their characteristics (qualitative ideas only). Transverse nature of electromagnetic waves.</li> <li>Electromagnetic spectrum (radio waves, microwaves, infrared, visible, ultraviolet, x-rays, gamma rays) including elementary facts about their uses.</li> </ul> </td> </tr> </tbody> </Table>
Unit 6
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Optics</td> <td> <ul> <li>Reflection of light, spherical mirrors, mirror formula. Refraction of light, total internal reflection and its applications optical fibres, refraction at spherical surfaces, lenses, thin lens formula, lens-maker’s formula. Magnification, power of a lens, combination of thin lenses in contact combination of a lens and a mirror. Refraction and dispersion of light through a prism.</li> <li>Scattering of light- blue colour of the sky and reddish appearance of the sun at sunrise and sunset.</li> <li>Optical instruments: Human eye, image formation and accommodation, correction of eye defects (myopia and hypermetropia) using lenses.</li> <li>Microscopes and astronomical telescopes (reflecting and refracting) and their magnifying powers.</li> <li>Wave optics: Wavefront and Huygens’ principle, reflection and refraction of plane wave at a plane surface using wavefronts.</li> <li>Proof of laws of reflection and refraction using Huygens’ principle.</li> <li>Interference, Young’s double hole experiment and expression for fringe width, coherent sources and sustained interference of light.</li> <li>Diffraction due to a single slit, width of central maximum. • Resolving power of microscopes and astronomical telescopes. Polarisation, plane polarized light; Brewster’s law, uses of plane polarized light and Polaroids.</li> </ul> </td> </tr> </tbody> </Table>
Unit 7
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Dual Nature of Matter and Radiation</td> <td> <ul> <li>Photoelectric effect, Hertz and Lenard’s observations; Einstein’s photoelectric equation- particle nature of light.</li> <li>Matter waves- wave nature of particles, de Broglie relation. Davisson-Ger</li> </ul> </td> </tr> </tbody> </Table>
Unit 8
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Atoms and Nuclei</td> <td> <ul> <li>Alpha- particle scattering experiments; Rutherford’s model of atom; Bohr model, energy levels, hydrogen spectrum. Composition and size of nucleus, atomic masses, isotopes, isobars; isotones.</li> <li>Radioactivity- alpha, beta and gamma particles/ rays and their properties decay law. Mass-energy relation, mass defect; binding energy per nucleon and its variation with mass number, nuclear fission and fusion.</li> </ul> </td> </tr> </tbody> </Table>
Unit 9
<Table className="accortable Table Table-striped style_Table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Electronic Devices</td> <td> <ul> <li>Energy bands in solids (qualitative ideas only), conductors, insulators and semiconductors; semiconductor diode- I-V characteristics in forward and reverse bias, diode as a rectifier; I-V characteristics of LED, diode, solar cell, and Zener diode; Zener diode as a voltage regulator.</li> <li>Junction transistor, transistor action, characteristics of a transistor; transistor as an amplifier (common emitter configuration) and oscillator. Logic gates (OR, AND, NOT, NAND and NOR). Transistor as a switch.</li> </ul> </td> </tr> </tbody> </Table>

<h4 className="text-danger">Important Topics NEET Physics</h4>
<h5 className="font-weight-bold">Physical World and Environment</h5>
<ul> <li><strong>Physics:</strong> Scope and Excitement; Nature of Physical Laws; Physics, Technology and Society.</li> <li><strong>Need for Measurement:</strong> Units of Measurement; Systems of Units; SI units, Fundamental and Derived units; Length, Mass and Time Measurements; Accuracy and Precision of Measuring Instruments; Errors in Measurement; Significant Figures.</li> <li>Dimensions of Physical Quantities, Dimensional Analysis and its Applications.</li> </ul>
<h5 className="font-weight-bold">Kinematics</h5>
<ul> <li>Frame of Reference, Motion in a Straight Line; Position-time Graph, Speed and Velocity; Uniform and Non-uniform Motion, Average Speed and Instantaneous Velocity; Uniformly Accelerated Motion, Velocity-time graphs.</li> <li>Elementary Concepts of Differentiation and Integration for Describing Motion; Scalar and Vector Quantities: Position and Displacement Vectors, General Vectors, General vectors and Notation, Equality of Vectors, Multiplication of Vectors by a Real Number; Addition and Subtraction of Vectors; Relative Velocity.</li> <li>Unit Vectors; Resolution of a Vector in a Plane - Rectangular Components.</li> <li>Scalar and Vector Products; Motion in a Plane; Cases of Uniform Velocity and Uniform Acceleration - Projectile Motion; Uniform Circular Motion.</li> </ul>
<h5 className="font-weight-bold">Laws of Motion</h5>
<ul> <li>Intuitive Concept of Force; Inertia, Newton’s First Law of Motion; Momentum and Newton’s Second Law of Motion; impulse; Newton’s Third Law of Motion. Law of Conservation of Linear Momentum and its Applications.</li> <li>Equilibrium of Concurrent Forces; Static and Kinetic Friction, Laws of Friction, Rolling friction, Lubrication.</li> <li>Dynamics of Uniform Circular Motion, Centripetal Force, Examples of Circular Motion (Vehicle on Level Circular Road, Vehicle on Banked Road).</li> </ul>
<h5 className="font-weight-bold">Electrostatics&nbsp;</h5>
<ul> <li>Electric Charges and their Conservation; Coulomb’s Law - Force between Two Point Charges, Forces between Multiple Charges; Superposition Principle and Continuous Charge Distribution.</li> <li>Electric Field, Electric Field due to a Point Charge, Electric Field Lines; Electric Dipole, Electric Field due to a Dipole; Torque on a Dipole in a Uniform Electric Field.</li> <li>Electric Flux, Statement of Gauss’s Theorem and its Applications to find Field due to Infinitely Long Straight Wire, Uniformly Charged Infinite Plane Sheet and Uniformly Charged Thin Spherical Shell (Field Inside and Outside)</li> <li>Electric Potential, Potential Difference, Electric Potential due to a Point Charge, Dipole and System of Charges: Equipotential Surfaces, Electrical Potential Energy of a System of Two Point Charges and of Electric Diploes in an Electrostatic Field.</li> <li>Conductors and Insulators, Free Charges and Bound Charges Inside a Conductor; Dielectrics and Electric Polarization, Capacitors and Capacitance, Combination of Capacitors in Series and in Parallel, Capacitance of a Parallel Plate Capacitor with and without Dielectric Medium between the Plates, Energy Stored in a Capacitor, Van de Graaff Generator.</li> </ul>
<h5 className="font-weight-bold">Magnetic Effects of Current and Magnetism</h5>
<ul> <li>Concept of Magnetic Field, Oersted’s Experiment; Biot-Savart Law and its Application to Current-carrying Circular Loop.</li> <li>&nbsp;Ampere’s Law and its Applications to Infinitely Long Straight Wire, Straight and Toroidal Solenoids; Force on a Moving Charge in Uniform Magnetic and Electric Fields; Cyclotron.</li> <li>Force on a Current-carrying Conductor in a Uniform Magnetic Field; Force Between Two Parallel Current-carrying Conductors Definition of Ampere; Torque Experienced by a Current Loop in a Magnetic Field; Moving Coil Galvanometer- its Current Sensitivity and Conversion to Ammeter and Voltmeter.</li> <li>Current Loop as a Magnetic Dipole and its Magnetic Dipole Moment; Magnetic Dipole Moment of a Revolving Electron; Magnetic Field Intensity due to a Magnetic Dipole (Bar Magnet) along its Axis and Perpendicular to its Axis; Torque on a Magnetic Dipole (Bar Magnet) in a Uniform Magnetic Field; Bar Magnet as an Equivalent Solenoid, Magnetic Field Lines; Earth’s Magnetic Field and Magnetic Elements.</li> <li>Para-, Dia-and Ferro-magnetic Substances with Examples.</li> <li>Electromagnetic and Factors Affecting their Strengths; Permanent Magnets.</li> </ul>
<h5 className="font-weight-bold">Electromagnetic Waves</h5>
<ul> <li>Need for Displacement Current.</li> <li>Electromagnetic Waves and their Characteristics (Qualitative Ideas only); Transverse Nature of Electromagnetic Waves.</li> <li>Electromagnetic Spectrum (Radio waves, Microwaves, Infrared, Visible, Ultraviolet, X-rays, Gamma rays) including Elementary Facts about their Uses.</li> </ul>

      {/* <Table hover>
        <thead>
          <tr>
            <th>#</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Username</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>Larry</td>
            <td>the Bird</td>
            <td>@twitter</td>
          </tr>
        </tbody>
      </Table>
     */}
    </div>
  );
}
