import React from 'react'
import { Table } from "reactstrap";

export default function Neetchemtable() {
    return (
        <div>
            <h5 className="text-danger">NEET Chemistry Syllabus 2022 Highlights</h5>
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <td>Total weightage</td> <td>25% of NEET Syllabus</td> </tr> <tr> <td>Subcategory</td> <td>Physical, Organic, and Inorganic Chemistry</td> </tr> <tr> <td>Number of questions asked</td> <td>Section A: 35, Section B: 15 (attempt only 10 from sec B)</td> </tr> <tr> <td>Marks allotted for each question</td> <td>4 marks for correct answer</td> </tr> <tr> <td>Negative marking</td> <td>1 marks will be reduced for wrong answer</td> </tr> <tr> <td>Total marks for Biology</td> <td>180 out of 720 marks</td> </tr> </tbody> </Table>
            <h5 className="text-danger">NEET Chemistry Syllabus 2022: Class 11</h5>
            Unit 1
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Some Basic Concepts of Chemistry</td> <td> <ul> <li>General Introduction: Important and scope of chemistry.</li> <li>Laws of chemical combination, Dalton’s atomic theory: concept of elements, atoms and molecules.</li> <li>Atomic and molecular masses. Mole concept and molar mass; percentage composition and empirical and molecular formula; chemical reactions, stoichiometry and calculations based on stoichiometry.</li> </ul> </td> </tr> </tbody> </Table>
            Unit 2
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Structure of Atom</td> <td> <ul> <li>Atomic number, isotopes and isobars. Concept of shells and subshells, dual nature of matter and light, de Broglie’s relationship, Heisenberg uncertainty principle, concept of orbital, quantum numbers, shapes of s,p and d orbitals, rules for filling electrons in orbitals- Aufbau principle, Pauli exclusion principles and Hund’s rule, electronic configuration of atoms, stability of half filled and completely filled orbitals.</li> </ul> </td> </tr> </tbody> </Table>
            Unit 3
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Classification of Elements and Periodicity in Properties</td> <td> <ul> <li>Modern periodic law and long form of periodic table, periodic trends in properties of elementsatomic radii, ionic radii, ionization enthalpy, electron gain enthalpy, electrone gativity, valence.</li> </ul> </td> </tr> </tbody> </Table>
            Unit 4
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Chemical Bonding and Molecular Structure</td> <td> <ul> <li>Valence electrons, ionic bond, covalent bond, bond parameters, Lewis structure, polar character of covalent bond, valence bond theory, resonance, geometry of molecules, VSEPR theory, concept of hybridization involving s, p and d orbitals and shapes of some simple molecules, molecular orbital theory of homonuclear diatomic molecules (qualitative idea only). Hydrogen bond.</li> </ul> </td> </tr> </tbody> </Table>
            Unit 5
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>States of Matter: Gases and Liquids</td> <td> <ul> <li>Three states of matter, intermolecular interactions, types of bonding, melting and boiling points, role of gas laws of elucidating the concept of the molecule, Boyle’s law, Charle’s law, Gay Lussac’s law, Avogadro’s law, ideal behaviour of gases, empirical derivation of gas equation. Avogadro number, ideal gas equation. Kinetic energy and molecular speeds (elementary idea), deviation from ideal behaviour, liquefaction of gases, critical temperature.</li> <li>Liquid State- Vapour pressure, viscosity and surface tension (qualitative idea only, no mathematical derivations).</li> </ul> </td> </tr> </tbody> </Table>
            Unit 6
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Thermodynamics</td> <td> <ul> <li>First law of thermodynamics-internal energy and enthalpy, heat capacity and specific heat, measurement of U and H, Hess’s law of constant heat summation, enthalpy of : bond dissociation, combustion, formation, atomization, sublimation, phase transition, ionization, solution and dilution.</li> <li>Introduction of entropy as state function, Second law of thermodynamics, Gibbs energy change for spontaneous and non-spontaneous process, criteria for equilibrium and spontaneity. • Third law of thermodynamics- Brief introduction.</li> </ul> </td> </tr> </tbody> </Table>
            Unit 7
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Equilibrium</td> <td> <ul> <li>Equilibrium in physical and chemical processes, dynamic nature of equilibrium, law of chemical equilibrium, equilibrium constant, factors affecting equilibrium- Le Chatelier’s principle; ionic equilibrium- ionization of acids and bases, strong and weak electrolytes, degree of ionization, ionization of polybasic acids, acid strength, concept of pH., Hydrolysis of salts (elementary idea)., buffer solutions, Henderson equation, solubility product, common ion effect (with illustrative examples).</li> </ul> </td> </tr> </tbody> </Table>
            Unit 8
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Redox Reactions</td> <td> <ul> <li>Concept of oxidation and oxidation and reduction, redox reactions oxidation number, balancing redox reactions in terms of loss and gain of electron and change in oxidation numbers.</li> </ul> </td> </tr> </tbody> </Table>
            Unit 9
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Hydrogen</td> <td> <ul> <li>Occurrence, isotopes, preparation, properties and uses of hydrogen; hydridesionic, covalent and interstitial; physical and chemical properties of water, heavy water; hydrogen peroxide-preparation, reactions, uses and structure.</li> </ul> </td> </tr> </tbody> </Table>
            Unit 10
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>s-Block Elements (Alkali and Alkaline earth metals)</td> <td> <ul> <li>Group I and group 2 elements:</li> <li>General introduction, electronic configuration, occurrence, anomalous properties of the first element of each group, diagonal relationship, trends in the variation of properties (such as ionization enthalpy, atomic and ionic radii), trends in chemical reactivity with oxygen, water, hydrogen and halogens; uses.</li> <li>Preparation and Properties of Some important Compounds:</li> <li>Sodium carbonate, sodium chloride, sodium hydroxide and sodium hydrogencarbonate, biological importance of sodium and potassium.</li> <li>Industrial use of lime and limestone, biological importance of Mg and Ca.</li> </ul> </td> </tr> </tbody> </Table>
            Unit 11
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Some p-Block Elements</td> <td> <ul> <li>General Introduction to p-Block Elements.</li> <li>Group 13 elements: General introduction, electronic configuration, occurrence, variation of properties, oxidation states, trends in chemical reactivity, anomalous properties of first element of the group; Boron, some important compounds: borax, boric acids, boron hydrides. Aluminium: uses, reactions with acids and alkalies.</li> <li>General 14 elements: General introduction, electronic configuration, occurrence, variation of properties, oxidation states, trends in chemical reactivity, anomalous behaviour of first element. Carbon, allotropic forms, physical and chemical properties: uses of some important compounds: oxides.</li> <li>Important compounds of silicon and a few uses: silicon tetrachloride, silicones, silicates and zeolites, their uses.</li> </ul> </td> </tr> </tbody> </Table>
            Unit 12
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Organic Chemistry- Some Basic Principles and Techniques</td> <td> <ul> <li>General introduction, methods of purification qualitative and quantitative analysis, classification and IUPAC nomenclature of organic compounds.</li> <li>Electronic displacements in a covalent bond: inductive effect, electromeric effect, resonance and hyper conjugation.</li> <li>Homolytic and heterolytic fission of a covalent bond: free radials, carbocations, carbanions; electrophiles and nucleophiles, types of organic reactions.</li> </ul> </td> </tr> </tbody> </Table>
            Unit 13
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Hydrocarbons</td> <td> <ul> <li>Alkanes- Nomenclature, isomerism, conformations (ethane only), physical properties, chemical reactions including free radical mechanism of halogenation, combustion and pyrolysis.</li> <li>Alkanes-Nomenclature, structure of double bond (ethene), geometrical isomerism, physical properties, methods of preparation: chemical reactions: addition of hydrogen, halogen, water, hydrogen halides (Markovnikov’s addition and peroxide effect), ozonolysis, oxidation, mechanism of electrophilic addition.</li> <li>Alkynes-Nomenclature, structure of triple bond (ethyne), physical properties, methods of preparation, chemical reactions: acidic character of alkynes, addition reaction of- hydrogen, halogens, hydrogen halides and water.</li> <li>Aromatic hydrocarbons- Introduction, IUPAC nomenclature; Benzene; resonance, aromaticity; chemical properties: mechanism of electrophilic substitution-Nitration sulphonation, halogenation, Friedel Craft’s alkylation and acylation; directive influence of functional group in mono-substituted benzene; carcinogenicity and toxicity.</li> </ul> </td> </tr> </tbody> </Table>
            Unit 14
            <Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Environmental Chemistry</td> <td> <ul> <li>Environmental pollution: Air, water and soil pollution, chemical reactions in atmosphere, smogs, major atmospheric pollutants; acid rain ozone and its reactions, effects of depletion of ozone layer, greenhouse effect and global warming-pollution due to industrial wastes; green chemistry as an alternative tool for reducing pollution, strategy for control of environmental pollution.</li> </ul> </td> </tr> </tbody> </Table>

            <h5 className="text-danger">NEET Chemistry Syllabus 2022: Class 12

            </h5>
Unit 1
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Solid State</td> <td> <ul> <li>Classification of solids based on different binding forces; molecular, ionic covalent and metallic solids, amorphous and crystalline solids (elementary idea), unit cell in two dimensional and three dimensional lattices, calculation of density of unit cell, packing in solids, packing efficiency, voids, number of atoms per unit cell in a cubic unit cell, point defects, electrical and magnetic properties, Band theory of metals, conductors, semiconductors and insulators.</li> </ul> </td> </tr> </tbody> </Table>
Unit 2
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Solutions</td> <td> <ul> <li>Types of solutions, expression of concentration of solutions of solids in liquids, solubility of gases in liquids, solid solutions, colligative properties- relative lowering of vapour pressure, Raoult’s law, elevation of boiling point, depression of freezing point, osmotic pressure, determination of molecular masses using colligative properties abnormal molecular mass. Van Hoff factor.</li> </ul> </td> </tr> </tbody> </Table>
Unit 3
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Electrochemistry</td> <td> <ul> <li>Redox reactions, conductance in electrolytic solutions, specific and molar conductivity variation of conductivity with concentration, kohlrausch’s Law, electrolysis and Laws of electrolysis (elementary idea), dry cell- electrolytic cells and Galvanic cells; lead accumulator, EMF of a cell, standard electrode potential, Relation between Gibbs energy change and EMF of a cell, fuel cells; corrosion</li> </ul> </td> </tr> </tbody> </Table>
Unit 4
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Chemical Kinetics</td> <td> <ul> <li>Rate of a reaction (average and instantaneous), factors affecting rates of reaction; concentration, temperature, catalyst; order and molecularity of a reaction; rate law and specific rate constant, integrated rate equations and half life (only for zero and first order reactions); concept of collision theory ( elementary idea, no mathematical treatment). Activation energy, Arrhenious equation</li> </ul> </td> </tr> </tbody> </Table>
Unit 5
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Surface Chemistry</td> <td> <ul> <li>Adsorption-physisorption and chemisorption; factors affecting adsorption of gases on solids, catalysis homogeneous and heterogeneous, activity and selectivity: enzyme catalysis; colloidal state: distinction between true solutions, colloids and suspensions; lyophillic, lyophobic multimolecular and macromolecular colloids; properties of colloids; Tyndall effect, Brownian movement, electrophoresis, coagulation; emulsions- types of emulsions</li> </ul> </td> </tr> </tbody> </Table>
Unit 6
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>General Principles and Processes of Isolation of Elements</td> <td> <ul> <li>Principles and methods of extraction- concentration, oxidation, reduction electrolytic method and refining; occurrence and principles of extraction of aluminium, copper, zinc and iron</li> </ul> </td> </tr> </tbody> </Table>
Unit 7
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>p- Block Elements</td> <td> <ul> <li>Group 15 elements: General introduction, electronic configuration, occurrence, oxidation states, trends in physical and chemical properties; preparation and properties of ammonia and nitric acid, oxides of nitrogen (structure only); Phosphorous- allotropic forms; compounds of phosphorous: preparation and properties of phosphine, halides (PCI3, PCI5) and oxoacids (elementary idea only)</li> <li>Group 16 elements: General introduction, electronic configuration, oxidation states, occurrence, trends in physical and chemical properties; dioxygen: preparation, properties and uses; classification of oxides; ozone. Sulphur – allotropic forms; compounds of sulphur: preparation, preparation, properties and uses of sulphur dioxide; sulphuric acid: industrial process of manufacture, properties and uses, oxoacids of sulphur (structures only)</li> <li>Group 17 elements: General introduction, electronic configuration, oxidation states, occurrence, trends in physical and chemical properties; compounds of halogens: preparation, properties and uses of chlorine and hydrochloric acid, interhalogen compounds oxoacids of halogens (structures only)</li> <li>Group 18 elements: General introduction, electronic configuration, occurrence, trends in physical and chemical properties, uses</li> </ul> </td> </tr> </tbody> </Table>
Unit 8
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>d and f Block Elements</td> <td> <ul> <li>General introduction, electronic configuration, characteristics of transition metals, general trends in properties of the first row transition metals- metallic character, ionization enthalpy, oxidation states, ionic radii, colour, catalytic property, magnetic properties, interstitial compounds, alloy formation. Preparation and properties of K2Cr2O7 and KMnO4</li> <li>Lanthanoids- electronic configuration, oxidation states, chemical reactivity, and lanthanoid contraction and its consequences</li> <li>Actinoids: Electronic configuration, oxidation states and comparison with lanthanoids</li> </ul> </td> </tr> </tbody> </Table>
Unit 9
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Coordination Compounds</td> <td> <ul> <li>Coordination compounds: Introduction, ligands, coordination number, colour, magnetic properties and shapes, IUPAC nomenclature of mononuclear coordination compounds, isomerism (structural and stereo) bonding, Werner’s theory VBT,CFT; importance of coordination compounds (in qualitative analysis, biological systems)</li> </ul> </td> </tr> </tbody> </Table>
Unit 10
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Haloalkanes and Haloarenes</td> <td> <ul> <li>Haloalkanes: Nomenclature, nature of C –X bond, physical and chemical properties, mechanism of substitution reactions. Optical rotation</li> <li>Haloarenes: Nature of C-X bond, substitution reactions (directive influence of halogen for monosubstituted compounds only) Uses and environment effects of – dichloromethane, trichloromethane, tetrachloromethane, iodoform, freons, DDT</li> </ul> </td> </tr> </tbody> </Table>
Unit 11
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Alcohols, Phenols and Ethers</td> <td> <ul> <li>Alcohols: Nomenclature, methods of preparation, physical and chemical properties (of primary alcohols only); identification of primary, secondary and tertiary alcohols; mechanism of dehydration, uses with special reference to methanol and ethanol</li> <li>Phenols: Nomenclature, methods of preparation, physical and chemical properties, acidic nature of phenol, electrophilic substitution reactions, uses of phenols</li> <li>Ethers: Nomenclature, methods of preparation, physical and chemical properties uses</li> </ul> </td> </tr> </tbody> </Table>
Unit 12
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Aldehydes, Ketones and Carboxylic Acids</td> <td> <ul> <li>Aldehydes and Ketones: Nomenclature, nature of carbonyl group, methods of preparation, physical and chemical properties; and mechanism of nucleophilic addition, reactivity of alpha hydrogen in aldehydes; uses</li> <li>Carboxylic Acids: Nomenclature, acidic nature, methods of preparation, physical and chemical properties; uses</li> </ul> </td> </tr> </tbody> </Table>
Unit 13
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Organic Compounds Containing Nitrogen</td> <td> <ul> <li>Amines: Nomenclature, classification, structure, methods of preparation, physical and chemical properties, uses, identification of primary secondary and tertiary amines.</li> <li>Cyanides and Isocyanides- will be mentioned at relevant places.</li> <li>Diazonium salts: Preparation, chemical reactions and importance in synthetic organic chemistry.</li> </ul> </td> </tr> </tbody> </Table>
Unit 14
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Biomolecules</td> <td> <ul> <li>Carbohydrates- Classification (aldoses and ketoses), monosaccharide (glucose and fructose), D.L. configuration, oligosaccharides (sucrose, lactose, maltose), polysaccharides (starch, cellulose, glycogen): importance.</li> <li>Proteins- Elementary idea of – amino acids, peptide bond, polypeptides, proteins, primary structure, secondary structure, tertiary structure and quaternary structure (qualitative idea only), denaturation of proteins; enzymes.</li> <li>Hormones- Elementary idea (excluding structure).</li> <li>Vitamins- Classification and function.</li> <li>Nucleic Acids: DNA and RNA</li> </ul> </td> </tr> </tbody> </Table>
Unit 15
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Polymers</td> <td> <ul> <li>Classification- Natural and synthetic, methods of polymerization (addition and condensation), copolymerization. Some important polymers: natural and synthetic like polyesters, bakelite; rubber, Biodegradable and non-biodegradable polymers.</li> </ul> </td> </tr> </tbody> </Table>
Unit 16
<Table  className="accortable table table-striped style_table"> <tbody> <tr> <th>Topic</th> <th>Sub-topics</th> </tr> <tr> <td>Chemistry in Everyday Life</td> <td> <ul> <li>Chemicals in medicines- analgesics, tranquilizers, antiseptics, disinfectants, antimicrobials, antifertility drugs, antibiotics, antacids, antihistamines.</li> <li>Chemicals in food- preservatives, artificial sweetening agents, elementary idea of antioxidants.</li> <li>Cleansing agents- soaps and detergents, cleansing action.</li> </ul> </td> </tr> </tbody> </Table>
        </div>
    )
}
