const mubarak = {
    objName: 'mubarak',
    name: 'Dr. Mubarak A Mujawar',
    photo: '/Mubarak-Mujawar2.jpg',
    position: 'Founder Director and CEO, 1to1 Guru',
    shortinfo: 'Dr. Mubarak A Mujawar received his PhD from Dublin City University, Ireland. After staying in Ireland and USA for more than a decade he returned to India to pursue is entrepreneurial ambitions.',
    education: ['PhD In Physics (University of Computer Science Pune)', 'Adjunct Professor, Florida International University, Miami, USA'],
    numVariable1: '15 Yrs',
    numVariable2: '4 Yrs',
    numVariable3: '',
    nameVariable1: 'Teaching Experience',
    nameVariable2: 'Industy Experience',
    nameVariable3: '',
    linkFacebook: '',
    linkInsta: '',
    linkLinkedin: '',
    info: ['Dr. Mubarak A Mujawar received his PhD from Dublin City University, Ireland. After staying in Ireland and USA for more than a decade he returned to India to pursue is entrepreneurial ambitions. He is the founding director and CEO of 1to1Guru, a subsidiary of AeduZEST Innovations Private Limited. He is also serving as a visiting faculty member at the Department of Electrical and Computer Engineering, Florida International University, Miami, USA. His current research interests are in Internet of Things, BioMEMS and Biosensors, low temperature plasma physics, and Physics and Engineering Education.'],
    researchInterest: [
        'IoT and IoMT (Internet of Medical Things)',
        'Wearable sensors and systems',
        'Micro/nanofabrication, MEMS, BioMEMS',
        'Low temperature plasma systems and diagnostics',
        'Physics and engineering education',
    ],
    teachingSubject: ['Engineering Orientation',
        'Circuits Analysis',
        'Electronics 1',
        'Electronics 2',
        'Internet of Things(IoT)',
        'IoT / Data Visualization',
        'Intro to ECE',
        'Advanced IoT / Wearable sensor Data Analytics',
    ],
    publication: [' S. K. Bhardwaj, M. A. Mujawar, Y. K. Mishra, N. Hickman, M. Chavali, A. Kaushik; Bio-inspired graphene-based nano-systems for biomedical applications; Nanotechnology; 32 (2020)502001 https://doi.org/10.1088/1361-6528/ac1bdb',
        'M. A. Mujawar, H. Gohel, S.K. Bhardwaj, S. Srinivasan, N. Hickman, A. Kaushik; Nano-enabled biosensing systems for intelligent healthcare: towards COVID-19 management; Materials Today Chemistry; 17 (2020), 100306 https://doi.org/10.1016/j.mtchem.2020.100306',
        'A. Sonawane, M. A. Mujawar, P. Manickam, S. Bhansali; Plasma-Induced Enhancement in Electronic Properties of Gold Nanoparticles: Application in Electrochemical Biosensing of Cortisol; ACS Applied Electronic Materials 3 (1), 230-237 https://doi.org/10.1021/acsaelm.0c00781',
        'Biosensing systems and methods using a FET; S. Bhansali, S.K. Pasha, M.A. Mujawar US Patent 10,739,305',
        'Apurva Sonawane, Sana Nasim, Pratik Shah, Sharan Ramaswamy, Guido Urizar, Pandiaraj Manickam, Mubarak A Mujawar, Shekhar Bhansali; Communication—Detection of Salivary Cortisol Using Zinc Oxide and Copper Porphyrin Composite Using Electrodeposition and Plasma-Assisted Deposition; ECS Journal of Solid State Science and Technology; 9 (2020) 061022 https://doi.org/10.1149/2162-8777/aba856',
        'A. Sonawane, M. A. Mujawar, S. Bhansali; Effects of cold atmospheric plasma treatment on the morphological and optical properties of plasmonic silver nanoparticles; Nanotechnology, 31 (2020) 365706',
        'A. Sonawane, M. A. Mujawar, S. Bhansali; Plasma Assisted Control of Nanoparticle Distribution for Enhancing the Electrochemical Activity of Electrodes; ECS; MA2020(2020)01',
        'A. Sonawane, M. A. Mujawar, S. Bhansali; Cold Atmospheric Plasma Annealing of Plasmonic Silver Nanoparticles; J. Electrochem. Soc.; 166 (9) (2019) B3084-B3090',
        'M. Thompson, M. Mujawar, Improving thrust density of electrohydrodynamic propulsion, APS (2019) YP10. 057',
        'A Kaushik, M. A. Mujawar, K Sharma; State-of Art functional biomaterials for tissue engineering; Frontiers in Materials 6(2019) 172',
        'Shivani Tiwari, Varsha Sharma, Mubarak Mujawar, Yogendra Kumar Mishra, Ajeet Kaushik, Anujit Ghosal; Biosensors for Epilepsy Management: State-of-Art and Future Aspects. Sensors; 19(7) (2019) 1525',
        'Pranjal Nautiyal, Mubarak Mujawar, Benjamin Boesl, Arvind Agarwal; In-situ mechanics of 3D graphene foam based ultra-stiff and flexible metallic metamaterial; Carbon 137 (2018) 502-510',
        'A. Kaushik, M. A. Mujawar; Point of Care Sensing Devices: Better Care For Everyone; Sensors 18 (2018) 4303',
        'A. Sonawane, M. A. Mujawar, S. Bhansali; Cold Atmospheric Plasma Annealing of Plasmonic Silver Nanoparticles; ECS; 88(1) (2018) 197-201',
        'Yogeswaran Umasankar, Mubarak Mujawar, Shekhar Bhansali; Towards Biosensor Enabled Smart Bandages for Wound Monitoring: Approach and Overview; 2018 IEEE Sensors (2018)1-4',
        'S. K. Pasha, M. A. Mujawar, A. Sonawane, S. Bhansali; Thin Film FETs on Flexible Substrates: a Case for Biosensing Application; ECS; 2 (2018) 145',
        'T.M. Khan, M.A. Mujawar, K.E. Siewerska, A. Pokle, T. Donnelly, N. McEvoy, G.S. Duesberg,J. G. Lunney; Atmospheric pulsed laser deposition and thermal annealing of plasmonic silver nanoparticle films; Nanotechnology; 28 (2017) 445601',
    ],
}
const bhushan = {
    objName: 'bhushan',
    name: 'Dr. Bhushankumar J. Patil',
    photo: '/bjp-photo.jpg',
    position: 'Interview Pannelist, 1to1 Guru',
    shortinfo: 'Dr. B. J. Patil has received his PhD in Physics from University of Pune, India. He is currently Working as Full Time Assistant Professor, at Abasaheb Garware College, Pune for graduate and postgraduate center ',
    education: ['PhD in Physics, (University of Pune, Pune)', 'Assistant Professor, Garware College, Pune'],
    numVariable1: '50',
    numVariable2: '3',
    numVariable3: '11 Yrs',
    nameVariable1: 'Research Publications',
    nameVariable2: 'PhD Students Supervised',
    nameVariable3: 'Teaching Experience',
    linkFacebook: '',
    linkInsta: '',
    linkLinkedin: '',
    info: [''],
    researchInterest: ['Accelerator Based Research for medical and industrial filed',
        'Application of nuclear radiation to Medical Physics',
        'Monte Carlo radiation transport simulation studies in materials',
        'Thermoluminescence Dosimetry and De - convolution of Thermoluminescence spectra',
        'Radiation effects on nanoparticles / nanowires',
        'Cross section measurement using Accelerator based neutron source'],
    teachingSubject: ['Nuclear Physics', 'Physics Principles', 'Mathematical Methods in Physics', 'Computational Physics',],
    publication: [
        'The flux weighted cross sections of Hf - 179(gamma, gamma) Hf - 179m and Hf - nat(gamma, x) Hf - 179m reactions at 8 MeV and 15 MeV bremsstrahlung end point energies GT Bholane, TS Ganesapandy, AB Phatangare, VD Bharud, BJ Patil,  APPLIED RADIATION AND ISOTOPES 174		(2021)',
        'The flux weighted cross sections of 179Hf(γ, γ’) 179mHf and natHf(γ, x) 179mHf reactions at 8 MeV and 15 MeV bremsstrahlung end point energies GT Bholane, TS Ganesapandy, AB Phatangare, VD Bharud, BJ Patil, ...         Applied Radiation and Isotopes 174, 109739	(2021)',
        'Establishment and dissemination of radiological standards in the field of diagnostic radiology in India VS Panyam, S Rakshit, SD Dhole, BJ Patil, AP Das, GA Kossery,  Journal of Medical Physics 46(1), 33 (2021)',
        'Tm-Tstop analysis and dosimetric properties of Ce doped BaB4O7 phosphor. Kishor H Gavhane, Mahesh S Bhadane, Akash S Bhoir, Preeti P Kulkarni, Bhushankumar J Patil, Vasant N Bhoraskar, Sanjay D Dhole, Shailendra S Dahiwale.   Journal of Alloys and Compounds 817, 152805 (2020)',
        'Design of electron beam bending magnet system for electron and photon therapy: A simulation approach. AA Shahzad, BJ Patil, ST Chavan, VN Bhoraskar, Sanjay Daga Dhole,.   Indian Journal of Pure & Applied Physics (IJPAP), 57(7), 492-497, (2019)',
        'Methodology adopted to establish diagnostic X-ray beam qualities. Vinatha S Panyam, Sougata Rakshit, Sanjay D Dhole, Bhushan J Patil, A Greeshma Kossery, Mukund S Kulkarni. Applied radiation and isotopes, vol 150, 164, (2019)',
        'TL properties of BaF2: Ce phosphor for high gamma ray dosimetry. Kishor H Gavhane, Mahesh S Bhadane, Akash P Jadhav, Bhushankumar J Patil, Vasant N Bhoraskar, Shailendra S Dahiwale, Sanjay D Dhole. Journal of Luminescence vol 209, 316-320, (2019)',
        'Production of 99Mo and 64Cu in a mixed field of photons and neutrons in a clinical electron linear accelerator. A Gopalakrishna, SV Suryanarayana, H Naik, BK Nayak, BJ Patil, S Devraju, RR Upreti, R Kinhikar, DD Deshpande, P Maletha, S Banerjee, A Saxena. Journal of Radioanalytical and Nuclear Chemistry, 317(3), 1409-1417, (2018)',
        'Measurement and uncertainty propagation of the (γ, n) reaction cross-section of 58Ni and 59Co at 15 MeV bremsstrahlung. Reetuparna Ghosh, Bioletty Lawriniang, Sylvia Badwar, Santhi Sheela Yerraguntla, Haladhara Naik, Bhushankumar J Patil, Yeshwant Naik, Saraswatula Venkata Suryanarayana, Betylda Jyrwa, Srinivasan Ganesan. Radiochimica Acta, 106(5), 345-354, (2018)',
        'Effect of lead foil on electron contamination to photon beam quality index: experimental and Monte Carlo study. AS Jagtap, SD Dhole, Nitin R Kakade, SD Sharma, BJ Patil. Journal of Medical Physics, 42(s1), 170, (2017)',
        'A Shahzad, AB Phatangare, VD Bharud, MS Bhadane, CD Tahakik, BJ Patil, SS Dahiwale, ST Chavan, SN Pethe, SD Dhole, VN Bhoraskar. Design and development of the 6–18 MeV electron beam system for medical and other applications. Radiation Effects and Defects in Solids, 172 (11-12), 931-951 (2017)',
        'KR Sature, BJ Patil, SS Dahiwale, VN Bhoraskar, SD Dhole. Development of computer code for deconvolution of thermoluminescence glow curve and DFT simulation. Journal of Luminescence, 192, 486-495 (2017)',
        'Mehdi S Barough, VD Bharud, BJ Patil, FMD Attar, VN Bhoraskar, SD Dhole. Measurement and Estimation of Cross Sections for 55Mn (n, γ) 56Mn and 65Cu (n, γ) 66Cu Reactions Using Accelerator-Based Neutron Source. Nuclear Science and Engineering, 187(3), 302-311 (2017).',
        'Nandkumar T Mandlik, Vasant N Bhoraskar, Bhushankumar J Patil, PD Sahare, Sanjay D Dhole, SS Dahiwale. Thermoluminescence studies of CaSO4: Eu nanophosphor for electron dosimetry. Indian Journal of Pure & Applied Physics (IJPAP), 55(6), 413-419, (2017). ',
        'Bhadane, M.S., Dahiwale, S.S., Sature, K.R., Patil, B.J., Bhoraskar, V.N., Dhole, S.D. TL studies of a sensitive CaNa2(SO4)2:Dy nanophoshor for gamma dosimetry. Radiation Measurements, 96, 1-7, (2017).',
        'Bhadane, M.S., Dahiwale, S.S., Sature, K.R., Patil, B.J., Mandlik, N.T., Bhoraskar, V.N., Dhole, S.D.. Synthesis and TSL properties of SnO2:Eu nanophosphor for high gamma dosimetry. Journal of Alloys and Compounds, 695, 1918-1923, (2017).',
        'Mahesh S. Bhadane, K. Hareesh, S.S. Dahiwale, K.R. Sature, B.J. Patil, K. Asokan, D. Kanjilal, V.N. Bhoraskar, S.D. Dhole, A highly sensitive CaF2:Dy nanophosphor as an efficient low energy ion Dosimetry. Nuclear Instruments and Methods in Physics Research B, 386, 61–69, (2016).',
        'AS Jagtap, T Palani Selvam, B.J. Patil*, ST Chavan, SN Pethe, Gauri Kulkarni, SS Dahiwale, VN Bhoraskar, SD Dhole, Monte Carlo based investigations of electron contamination from telecobalt unit head in build up region and its impact on surface dose. Applied Radiation and Isotopes, 118, 175-181, (2016).',
        'AS Jagtap, B.J. Patil, SS Dahiwale, VN Bhoraskar, SD Dhole, Electron depth dose curves in inhomogeneous medium for radiation therapy: A simulation approach. Physica Medica, 32, 266-267, (2016).',
        'M.S.Bhadane, N.T. Mandlik, B.J.Patil, S.S. Dahiwale, K.R. Sature, V.N. Bhoraskar, S.D. Dhole, CaSO4:Dy microphosphor for thermal neutron dosimetry. Journal of Luminescence, 170, 226-230, (2016). ',
        'M.S. Barough, B.J. Patil, V.N. Bhoraskar, S.D. Dhole, Measurement and estimation of isomeric cross section of 137Ba(n, n’)137mBa reaction using accelerator based neutron source. Annals of Nuclear Energy, 63,209-214, (2014).',
        'Nandkumar Mandlik, P. D. Sahare, B. J. Patil, V. N. Bhoraskar, S. D. Dhole. Thermoluminescence study of K2Ca2(SO4)3:Cu nanophosphor for gamma ray dosimetry. Nucl. Instr. Meth B, 315, 273-277, (2013). ',
        'M.S. Barough, B.J. Patil, V.N. Bhoraskar, S.D. Dhole, Measurement of cross section of (n, g) reaction for, iodine, sodium and vanadium in the energy range 1 keV to 4 MeV using accelerator based neutron source. Annals of Nuclear Energy, 59(1), 25-30, (2013).',
        'B. J. Patil, A. J Patil, S. T. Chavan, S. N. Pethe, R. Krishnan, V. N. Bhoraskar, S. D. Dhole, FLUKA Simulation of 15 MeV Linear Accelerator Based Thermal Neutron Source for Radiography. Indian Journal of Pure and Applied Physics, 50(11), 814-817, (2012). ',
        'B. Lalremruata, N. Otuka, G. J. Tambave, V. K. Mulik, B. J. Patil, S. D. Dhole, A. Saxena, S. Ganesan, and V. N. Bhoraskar, 2012.  Systematic study of (n, p) reaction cross sections from the reaction threshold to 20 MeV. Physical Review C 85, 024624, (2012).',
        'Avinash V. Deore, B. J. Patil, V. N. Bhoraskar, S. D. Dhole, Design, development and characterization of a tetrode type electron gun system for generation of low energy electrons. Indian Journal of Pure and Applied Physics, 50(7), 482-485, (2012). ',
        'B. J. Patil, S. T. Chavan, S. N. Pethe, R. Krishnan, V. N. Bhoraskar, S. D. Dhole, Design of 6 MeV Linear Accelerator Based Thermal Neutron Source: FLUKA simulation and experiment. Applied Radiation Isotopes, 70(1) 149-155, (2012).',
        'N.T. Mandlik, V.N. Bhoraskar, P.D. Sahare, B. J. Patil, V. Kumar, M.S. Kulkarni, S.D. Dhole, Thermoluminescence and Photoluminescence study of CaSO4:Dy nanophosphor for 6 MeV energy electron dosimetry, Radiation Protection and Environment, 34(3), 185, (2011).   ',
        'B. J. Patil, S. T. Chavan, S. N. Pethe, R. Krishnan, V. B. Bhoraskar, S. D. Dhole, Estimation of Neutron Production from Accelerator Head Assembly of 15 MV Medical LINAC using FLUKA Simulations. Nucl. Instr. Meth B, 269(24) 3261-3265, (2011). ',
        'B. J. Patil, S. T. Chavan, S. N. Pethe, R. Krishnan, V. N. Bhoraskar, S. D. Dhole, 2010. Simulation of e-g-n targets by FLUKA and measurement of neutron flux at various angles for accelerator based neutron source. Annals of Nuclear Energy, 37(10) 1369-1377, (2010).',
        'B. J. Patil, S. T. Chavan, S. N. Pethe, R. Krishnan, S. D. Dhole, Measurement of angular distribution of neutron flux for the 6 MeV race-track Microtron accelerator based pulsed neutron source. Applied Radiation of Isotopes, 68(9) 1743-1745, (2010).',
        ' B. J. Patil, S. S. Dahiwale, S. T. Chavan, S. N. Pethe, V. F. Khan, R. Krishnan, V. N. Bhoraskar and S. D. Dhole, Proposed Pulsed Neutron Source for Radiotherapy and Radiography. Journal of Medical Physics, Vol 32 |Suppl|, s38, (2007).',
        'B. J. Patil, S. K. Mahapatra, S. N. Pethe, S. T. Chavan, V. N. Bhoraskar, S. D. Dhole, Angular Distribution of Bremsstrahlung radiation from 6 and 15 MeV Pulsed electron beam incident on Tungsten target. Journal of Medical Physics, Vol 31 (3), 212, (2006).',
        'S. K. Mahapatra, B. J. Patil, S. T. Chavan, V. N. Bhoraskar, S. D. Dhole, Automation of Low Energy Electron Irradiation System for Medical Application. Journal of Medical Physics, 31 (3), 211, (2006)',
        'B. J. Patil, S. N. Pethe, S. T. Chavan, V. N. Bhoraskar, S. D. Dhole, Useful Bremsstrahlung spectra from linear and circular accelerators for radiation therapy: calculated and simulated case. Journal of Medical Physics, Vol 30 (4), 298, (2005).',
        'Full Papers in International Conference Proceedings',
        'Establishment of standard radiation beam qualities used in diagnostic radiology. Vinatha S Panyam, Sougata Rakshit, KA Greeshma, MS Kulkarni, Sanjay D Dhole, BJ Patil. Proceedings of the thirty-third IARP international conference on developments towards improvement of radiological surveillance at nuclear facilities and environment: book of abstracts (2018)',
        'Measurement of (n, 2n) cross section of metastable state for a short half lived of 140Ce at 14.8 MeV neutron energy. Vishal D Bharud, SS Dahiwale, VN Bhoraskar, SD Dhole, FMD Attar, BJ Patil. Proceedings of the international conference on high energy radiation and applications: abstracts and souvenir (2017)',
        'B. J. Patil, S. T. Chavan, S. N. Pethe, S.S. Dahiwale, V. N. Bhoraskar and S. D. Dhole Neutron Contamination in Accelerator Head Assembly of 15 MV Medical LINAC, Abstract Book, National Symposium of Medical Biophysics, 29 (2015). ',
        'Vishal D. Bharud, B. J. Patil, S. S. Dahiwale, V. N. Bhoraskar, S. D. Dhole, Effective Neutron Dosimetry Using 23Na Concentration in the Human Blood, Abstract Book, National Symposium of Medical Biophysics, 67 (2015). ',
        'A.S. Jagtap, B.J. Patil, G.R. Kulkarni, S. S. Dahiwale, V. N. Bhoraskar and S. Dhole. Energy spectrum and angular distribution of photon from different targets using Monte Carlo simulation for radiation therapy, Abstract Book, National Symposium of Medical Biophysics,74 (2015)',
        'B. J. Patil, Mahesh S. Bhadane, N. T. Mandlik, S. S. Dahiwale, M. S. Kulkarni, B. C. Bhatt, V. N. Bhoraskar and S. D. Dhole, Thermoluminescence response of K2Ca2(SO4)3 nanophosphor Co-doped with Eu and Ce for gamma ray dosimetry, SOLID STATE PHYSICS: AIP Conference Proceedings, 1665, 050109 (2015);',
        'Mahesh S. Bhadane, B. J. Patil, S. S. Dahiwale, M. S. Kulkarni, B. C. Bhatt, V. N. Bhoraskar, and S. D. Dhole, Synthesis and characterization of CaF2:Dy nanophosphor for dosimetric application, SOLID STATE PHYSICS: AIP Conference Proceedings, 1665, 050113 (2015)',
        'Nandkumar Mandlik, B. J. Patil, V. N. Bhoraskar, P. D. Sahare, and S. D. Dhole Thermoluminescence of nanocrystalline CaSO4: Dy for gamma dosimetry and calculation of trapping parameters using deconvolution method., SOLID STATE PHYSICS: AIP Conference Proceedings 1591, 369 (2014)',
        'Amol Jagtap, B. J. Patil, T. Palani Selvam, S.D. Dhole, Investigation of surface doses and central axis depth doses of Theratron 780E telecobalt unit using BEAMnrc Monte Carlo code. Proceeding of 33rd National Conference on Association of Medical Physicists of India (AMPICON-12), Mangalore, P073, (2012).',
        'S. Akhter, B.J. Patil, V.N. Bhoraskar, S.T. Chavan, R. Krishnan, S.N. Pethe, S.D. Dhole, 270 degree Electron Beam Bending System using Two Sector Magnets for Therapy Application. Proceedings of IBIC2012, Tsukuba, Japan, MOPA02, 50-53, (2012). (http://accelconf.web.cern.ch/accelconf/IBIC2012/papers/mopa02.pdf) ',
        'S.D. Dhole, B.J. Patil, V.N. Bhoraskar, N.S. Shinde, 2012. An Electron Beam Profile Monitor for the Race-track Microtron. Proceedings of IBIC2012, Tsukuba, Japan, MOPA04, 54-56, (2012). Proceedings of IBIC2012, (http://accelconf.web.cern.ch/accelconf/IBIC2012/papers/mopa04.pdf)',
        'B.J. Patil, S.D. Dhole, S. Akhter, V.N. Bhoraskar, N.S. Shinde, 2012. Pulsed Electron Beam Current and Flux Monitor for the Race-track Microtron. Proceedings of IBIC2012, Tsukuba, Japan, TUPA06, 337-340, (2012). (http://accelconf.web.cern.ch/accelconf/IBIC2012/papers/tupa06.pdf) ',
        'B. J. Patil, A. J Patil, S. T. Chavan, S. N. Pethe, R. Krishnan, V. N. Bhoraskar, S. D. Dhole, Collimator Design of 15 MeV Linear Accelerator Based Thermal Neutron Source for Radiography. Proc. of 2011 Particle Accelerator conference, New York, NY, USA, THP009, 2154-2156, (2011). (http://accelconf.web.cern.ch/accelconf/PAC2011/papers/thp009.pdf). ',
        'B. J. Patil, S. T. Chavan, S. N. Pethe, R. Krishnan, V. N. Bhoraskar, S. D. Dhole., Optimization of Dual Scattering Foil for 6 To 20 MeV Electron Beam Radiotherapy. Proc. of 2011 Particle Accelerator conference, New York, NY, USA, THP010, 2157-2159, (2011) (http://accelconf.web.cern.ch/accelconf/PAC2011/papers/thp010.pdf).',
        'N. L. Mathakari, B. J. Patil, S. S. Dahiwale, V.N. Bhoraskar, S. D. Dhole, 6 MeV Electron Beam Induced Diffusion of Iodine in Isotactic Polypropylene. SPIE Proceeding of Penetrating Radiation Systems and Applications XII, Vol. 8144, 20, (2011), Editor(s): Gary P. Grim; Richard C. Schirato. (http://spie.org/x648.html?product_id=884227&origin_id=x4325&InvalidQS=go.y=12&end_volume_number=8199&InvalidQS=go.x=8&InvalidQS=go.y=10&start_at=41&start_volume_number=8100) (ISBN:9780819487544)',
        'B. J. Patil, S. D. Dhole, Studies on (i) Characterization of Bremsstrahlung Spectra from High Z elements and (ii) Development of Neutron Source Using MeV Pulsed Electron Beam and Their Applications. Proc. of DAE Symposium on Nuclear Physics, Vol. 55, 828, (2010) (http://sympnp.org/proceedings/index.php)& also published online at Medical Physics Journal. http://www.medphys.org/PhdAbstracts/  .  ',

    ]
}
const adinath = {
    objName: 'adinath',
    name: 'Dr. Adinath M. Funde',
    photo: '/adinath.jpeg',
    position: 'Content Advisor, 1to1 Guru',
    shortinfo: 'Dr. A. M. Funde has received his PhD in Physics from University of Pune, India. He is currently Working as Full Time Assistant Professor, at Abasaheb Garware College, Pune for graduate and postgraduate center ',
    education: ['PhD in Physics, (University of Pune, Pune)', 'Assistant Professor, Center for Energy Studies, SPPU'],
    numVariable1: '66',
    numVariable2: '4',
    numVariable3: '11 Yrs',
    nameVariable1: 'Research Publications',
    nameVariable2: 'PhD Students Supervised',
    nameVariable3: 'Teaching Experience',
    linkFacebook: '',
    linkInsta: '',
    linkLinkedin: '',
    info: [''],
    researchInterest: ['Accelerator Based Research for medical and industrial filed',
        'Application of nuclear radiation to Medical Physics',
        'Monte Carlo radiation transport simulation studies in materials',
        'Thermoluminescence Dosimetry and De - convolution of Thermoluminescence spectra',
        'Radiation effects on nanoparticles / nanowires',
        'Cross section measurement using Accelerator based neutron source'],
    teachingSubject: ['Nuclear Physics', 'Physics Principles', 'Mathematical Methods in Physics', 'Computational Physics',],
    publication: [
        'The flux weighted cross sections of Hf - 179(gamma, gamma) Hf - 179m and Hf - nat(gamma, x) Hf - 179m reactions at 8 MeV and 15 MeV bremsstrahlung end point energies GT Bholane, TS Ganesapandy, AB Phatangare, VD Bharud, BJ Patil,  APPLIED RADIATION AND ISOTOPES 174		(2021)',
        'The flux weighted cross sections of 179Hf(γ, γ’) 179mHf and natHf(γ, x) 179mHf reactions at 8 MeV and 15 MeV bremsstrahlung end point energies GT Bholane, TS Ganesapandy, AB Phatangare, VD Bharud, BJ Patil, ...         Applied Radiation and Isotopes 174, 109739	(2021)',
        'Establishment and dissemination of radiological standards in the field of diagnostic radiology in India VS Panyam, S Rakshit, SD Dhole, BJ Patil, AP Das, GA Kossery,  Journal of Medical Physics 46(1), 33 (2021)',
        'Tm-Tstop analysis and dosimetric properties of Ce doped BaB4O7 phosphor. Kishor H Gavhane, Mahesh S Bhadane, Akash S Bhoir, Preeti P Kulkarni, Bhushankumar J Patil, Vasant N Bhoraskar, Sanjay D Dhole, Shailendra S Dahiwale.   Journal of Alloys and Compounds 817, 152805 (2020)',
        'Design of electron beam bending magnet system for electron and photon therapy: A simulation approach. AA Shahzad, BJ Patil, ST Chavan, VN Bhoraskar, Sanjay Daga Dhole,.   Indian Journal of Pure & Applied Physics (IJPAP), 57(7), 492-497, (2019)',
        'Methodology adopted to establish diagnostic X-ray beam qualities. Vinatha S Panyam, Sougata Rakshit, Sanjay D Dhole, Bhushan J Patil, A Greeshma Kossery, Mukund S Kulkarni. Applied radiation and isotopes, vol 150, 164, (2019)',
        'TL properties of BaF2: Ce phosphor for high gamma ray dosimetry. Kishor H Gavhane, Mahesh S Bhadane, Akash P Jadhav, Bhushankumar J Patil, Vasant N Bhoraskar, Shailendra S Dahiwale, Sanjay D Dhole. Journal of Luminescence vol 209, 316-320, (2019)',
        'Production of 99Mo and 64Cu in a mixed field of photons and neutrons in a clinical electron linear accelerator. A Gopalakrishna, SV Suryanarayana, H Naik, BK Nayak, BJ Patil, S Devraju, RR Upreti, R Kinhikar, DD Deshpande, P Maletha, S Banerjee, A Saxena. Journal of Radioanalytical and Nuclear Chemistry, 317(3), 1409-1417, (2018)',
        'Measurement and uncertainty propagation of the (γ, n) reaction cross-section of 58Ni and 59Co at 15 MeV bremsstrahlung. Reetuparna Ghosh, Bioletty Lawriniang, Sylvia Badwar, Santhi Sheela Yerraguntla, Haladhara Naik, Bhushankumar J Patil, Yeshwant Naik, Saraswatula Venkata Suryanarayana, Betylda Jyrwa, Srinivasan Ganesan. Radiochimica Acta, 106(5), 345-354, (2018)',
        'Effect of lead foil on electron contamination to photon beam quality index: experimental and Monte Carlo study. AS Jagtap, SD Dhole, Nitin R Kakade, SD Sharma, BJ Patil. Journal of Medical Physics, 42(s1), 170, (2017)',
        'A Shahzad, AB Phatangare, VD Bharud, MS Bhadane, CD Tahakik, BJ Patil, SS Dahiwale, ST Chavan, SN Pethe, SD Dhole, VN Bhoraskar. Design and development of the 6–18 MeV electron beam system for medical and other applications. Radiation Effects and Defects in Solids, 172 (11-12), 931-951 (2017)',
        'KR Sature, BJ Patil, SS Dahiwale, VN Bhoraskar, SD Dhole. Development of computer code for deconvolution of thermoluminescence glow curve and DFT simulation. Journal of Luminescence, 192, 486-495 (2017)',
        'Mehdi S Barough, VD Bharud, BJ Patil, FMD Attar, VN Bhoraskar, SD Dhole. Measurement and Estimation of Cross Sections for 55Mn (n, γ) 56Mn and 65Cu (n, γ) 66Cu Reactions Using Accelerator-Based Neutron Source. Nuclear Science and Engineering, 187(3), 302-311 (2017).',
        'Nandkumar T Mandlik, Vasant N Bhoraskar, Bhushankumar J Patil, PD Sahare, Sanjay D Dhole, SS Dahiwale. Thermoluminescence studies of CaSO4: Eu nanophosphor for electron dosimetry. Indian Journal of Pure & Applied Physics (IJPAP), 55(6), 413-419, (2017). ',
        'Bhadane, M.S., Dahiwale, S.S., Sature, K.R., Patil, B.J., Bhoraskar, V.N., Dhole, S.D. TL studies of a sensitive CaNa2(SO4)2:Dy nanophoshor for gamma dosimetry. Radiation Measurements, 96, 1-7, (2017).',
        'Bhadane, M.S., Dahiwale, S.S., Sature, K.R., Patil, B.J., Mandlik, N.T., Bhoraskar, V.N., Dhole, S.D.. Synthesis and TSL properties of SnO2:Eu nanophosphor for high gamma dosimetry. Journal of Alloys and Compounds, 695, 1918-1923, (2017).',
        'Mahesh S. Bhadane, K. Hareesh, S.S. Dahiwale, K.R. Sature, B.J. Patil, K. Asokan, D. Kanjilal, V.N. Bhoraskar, S.D. Dhole, A highly sensitive CaF2:Dy nanophosphor as an efficient low energy ion Dosimetry. Nuclear Instruments and Methods in Physics Research B, 386, 61–69, (2016).',
        'AS Jagtap, T Palani Selvam, B.J. Patil*, ST Chavan, SN Pethe, Gauri Kulkarni, SS Dahiwale, VN Bhoraskar, SD Dhole, Monte Carlo based investigations of electron contamination from telecobalt unit head in build up region and its impact on surface dose. Applied Radiation and Isotopes, 118, 175-181, (2016).',
        'AS Jagtap, B.J. Patil, SS Dahiwale, VN Bhoraskar, SD Dhole, Electron depth dose curves in inhomogeneous medium for radiation therapy: A simulation approach. Physica Medica, 32, 266-267, (2016).',
        'M.S.Bhadane, N.T. Mandlik, B.J.Patil, S.S. Dahiwale, K.R. Sature, V.N. Bhoraskar, S.D. Dhole, CaSO4:Dy microphosphor for thermal neutron dosimetry. Journal of Luminescence, 170, 226-230, (2016). ',
        'M.S. Barough, B.J. Patil, V.N. Bhoraskar, S.D. Dhole, Measurement and estimation of isomeric cross section of 137Ba(n, n’)137mBa reaction using accelerator based neutron source. Annals of Nuclear Energy, 63,209-214, (2014).',
        'Nandkumar Mandlik, P. D. Sahare, B. J. Patil, V. N. Bhoraskar, S. D. Dhole. Thermoluminescence study of K2Ca2(SO4)3:Cu nanophosphor for gamma ray dosimetry. Nucl. Instr. Meth B, 315, 273-277, (2013). ',
        'M.S. Barough, B.J. Patil, V.N. Bhoraskar, S.D. Dhole, Measurement of cross section of (n, g) reaction for, iodine, sodium and vanadium in the energy range 1 keV to 4 MeV using accelerator based neutron source. Annals of Nuclear Energy, 59(1), 25-30, (2013).',
        'B. J. Patil, A. J Patil, S. T. Chavan, S. N. Pethe, R. Krishnan, V. N. Bhoraskar, S. D. Dhole, FLUKA Simulation of 15 MeV Linear Accelerator Based Thermal Neutron Source for Radiography. Indian Journal of Pure and Applied Physics, 50(11), 814-817, (2012). ',
        'B. Lalremruata, N. Otuka, G. J. Tambave, V. K. Mulik, B. J. Patil, S. D. Dhole, A. Saxena, S. Ganesan, and V. N. Bhoraskar, 2012.  Systematic study of (n, p) reaction cross sections from the reaction threshold to 20 MeV. Physical Review C 85, 024624, (2012).',
        'Avinash V. Deore, B. J. Patil, V. N. Bhoraskar, S. D. Dhole, Design, development and characterization of a tetrode type electron gun system for generation of low energy electrons. Indian Journal of Pure and Applied Physics, 50(7), 482-485, (2012). ',
        'B. J. Patil, S. T. Chavan, S. N. Pethe, R. Krishnan, V. N. Bhoraskar, S. D. Dhole, Design of 6 MeV Linear Accelerator Based Thermal Neutron Source: FLUKA simulation and experiment. Applied Radiation Isotopes, 70(1) 149-155, (2012).',
        'N.T. Mandlik, V.N. Bhoraskar, P.D. Sahare, B. J. Patil, V. Kumar, M.S. Kulkarni, S.D. Dhole, Thermoluminescence and Photoluminescence study of CaSO4:Dy nanophosphor for 6 MeV energy electron dosimetry, Radiation Protection and Environment, 34(3), 185, (2011).   ',
        'B. J. Patil, S. T. Chavan, S. N. Pethe, R. Krishnan, V. B. Bhoraskar, S. D. Dhole, Estimation of Neutron Production from Accelerator Head Assembly of 15 MV Medical LINAC using FLUKA Simulations. Nucl. Instr. Meth B, 269(24) 3261-3265, (2011). ',
        'B. J. Patil, S. T. Chavan, S. N. Pethe, R. Krishnan, V. N. Bhoraskar, S. D. Dhole, 2010. Simulation of e-g-n targets by FLUKA and measurement of neutron flux at various angles for accelerator based neutron source. Annals of Nuclear Energy, 37(10) 1369-1377, (2010).',
        'B. J. Patil, S. T. Chavan, S. N. Pethe, R. Krishnan, S. D. Dhole, Measurement of angular distribution of neutron flux for the 6 MeV race-track Microtron accelerator based pulsed neutron source. Applied Radiation of Isotopes, 68(9) 1743-1745, (2010).',
        ' B. J. Patil, S. S. Dahiwale, S. T. Chavan, S. N. Pethe, V. F. Khan, R. Krishnan, V. N. Bhoraskar and S. D. Dhole, Proposed Pulsed Neutron Source for Radiotherapy and Radiography. Journal of Medical Physics, Vol 32 |Suppl|, s38, (2007).',
        'B. J. Patil, S. K. Mahapatra, S. N. Pethe, S. T. Chavan, V. N. Bhoraskar, S. D. Dhole, Angular Distribution of Bremsstrahlung radiation from 6 and 15 MeV Pulsed electron beam incident on Tungsten target. Journal of Medical Physics, Vol 31 (3), 212, (2006).',
        'S. K. Mahapatra, B. J. Patil, S. T. Chavan, V. N. Bhoraskar, S. D. Dhole, Automation of Low Energy Electron Irradiation System for Medical Application. Journal of Medical Physics, 31 (3), 211, (2006)',
        'B. J. Patil, S. N. Pethe, S. T. Chavan, V. N. Bhoraskar, S. D. Dhole, Useful Bremsstrahlung spectra from linear and circular accelerators for radiation therapy: calculated and simulated case. Journal of Medical Physics, Vol 30 (4), 298, (2005).',
        'Full Papers in International Conference Proceedings',
        'Establishment of standard radiation beam qualities used in diagnostic radiology. Vinatha S Panyam, Sougata Rakshit, KA Greeshma, MS Kulkarni, Sanjay D Dhole, BJ Patil. Proceedings of the thirty-third IARP international conference on developments towards improvement of radiological surveillance at nuclear facilities and environment: book of abstracts (2018)',
        'Measurement of (n, 2n) cross section of metastable state for a short half lived of 140Ce at 14.8 MeV neutron energy. Vishal D Bharud, SS Dahiwale, VN Bhoraskar, SD Dhole, FMD Attar, BJ Patil. Proceedings of the international conference on high energy radiation and applications: abstracts and souvenir (2017)',
        'B. J. Patil, S. T. Chavan, S. N. Pethe, S.S. Dahiwale, V. N. Bhoraskar and S. D. Dhole Neutron Contamination in Accelerator Head Assembly of 15 MV Medical LINAC, Abstract Book, National Symposium of Medical Biophysics, 29 (2015). ',
        'Vishal D. Bharud, B. J. Patil, S. S. Dahiwale, V. N. Bhoraskar, S. D. Dhole, Effective Neutron Dosimetry Using 23Na Concentration in the Human Blood, Abstract Book, National Symposium of Medical Biophysics, 67 (2015). ',
        'A.S. Jagtap, B.J. Patil, G.R. Kulkarni, S. S. Dahiwale, V. N. Bhoraskar and S. Dhole. Energy spectrum and angular distribution of photon from different targets using Monte Carlo simulation for radiation therapy, Abstract Book, National Symposium of Medical Biophysics,74 (2015)',
        'B. J. Patil, Mahesh S. Bhadane, N. T. Mandlik, S. S. Dahiwale, M. S. Kulkarni, B. C. Bhatt, V. N. Bhoraskar and S. D. Dhole, Thermoluminescence response of K2Ca2(SO4)3 nanophosphor Co-doped with Eu and Ce for gamma ray dosimetry, SOLID STATE PHYSICS: AIP Conference Proceedings, 1665, 050109 (2015);',
        'Mahesh S. Bhadane, B. J. Patil, S. S. Dahiwale, M. S. Kulkarni, B. C. Bhatt, V. N. Bhoraskar, and S. D. Dhole, Synthesis and characterization of CaF2:Dy nanophosphor for dosimetric application, SOLID STATE PHYSICS: AIP Conference Proceedings, 1665, 050113 (2015)',
        'Nandkumar Mandlik, B. J. Patil, V. N. Bhoraskar, P. D. Sahare, and S. D. Dhole Thermoluminescence of nanocrystalline CaSO4: Dy for gamma dosimetry and calculation of trapping parameters using deconvolution method., SOLID STATE PHYSICS: AIP Conference Proceedings 1591, 369 (2014)',
        'Amol Jagtap, B. J. Patil, T. Palani Selvam, S.D. Dhole, Investigation of surface doses and central axis depth doses of Theratron 780E telecobalt unit using BEAMnrc Monte Carlo code. Proceeding of 33rd National Conference on Association of Medical Physicists of India (AMPICON-12), Mangalore, P073, (2012).',
        'S. Akhter, B.J. Patil, V.N. Bhoraskar, S.T. Chavan, R. Krishnan, S.N. Pethe, S.D. Dhole, 270 degree Electron Beam Bending System using Two Sector Magnets for Therapy Application. Proceedings of IBIC2012, Tsukuba, Japan, MOPA02, 50-53, (2012). (http://accelconf.web.cern.ch/accelconf/IBIC2012/papers/mopa02.pdf) ',
        'S.D. Dhole, B.J. Patil, V.N. Bhoraskar, N.S. Shinde, 2012. An Electron Beam Profile Monitor for the Race-track Microtron. Proceedings of IBIC2012, Tsukuba, Japan, MOPA04, 54-56, (2012). Proceedings of IBIC2012, (http://accelconf.web.cern.ch/accelconf/IBIC2012/papers/mopa04.pdf)',
        'B.J. Patil, S.D. Dhole, S. Akhter, V.N. Bhoraskar, N.S. Shinde, 2012. Pulsed Electron Beam Current and Flux Monitor for the Race-track Microtron. Proceedings of IBIC2012, Tsukuba, Japan, TUPA06, 337-340, (2012). (http://accelconf.web.cern.ch/accelconf/IBIC2012/papers/tupa06.pdf) ',
        'B. J. Patil, A. J Patil, S. T. Chavan, S. N. Pethe, R. Krishnan, V. N. Bhoraskar, S. D. Dhole, Collimator Design of 15 MeV Linear Accelerator Based Thermal Neutron Source for Radiography. Proc. of 2011 Particle Accelerator conference, New York, NY, USA, THP009, 2154-2156, (2011). (http://accelconf.web.cern.ch/accelconf/PAC2011/papers/thp009.pdf). ',
        'B. J. Patil, S. T. Chavan, S. N. Pethe, R. Krishnan, V. N. Bhoraskar, S. D. Dhole., Optimization of Dual Scattering Foil for 6 To 20 MeV Electron Beam Radiotherapy. Proc. of 2011 Particle Accelerator conference, New York, NY, USA, THP010, 2157-2159, (2011) (http://accelconf.web.cern.ch/accelconf/PAC2011/papers/thp010.pdf).',
        'N. L. Mathakari, B. J. Patil, S. S. Dahiwale, V.N. Bhoraskar, S. D. Dhole, 6 MeV Electron Beam Induced Diffusion of Iodine in Isotactic Polypropylene. SPIE Proceeding of Penetrating Radiation Systems and Applications XII, Vol. 8144, 20, (2011), Editor(s): Gary P. Grim; Richard C. Schirato. (http://spie.org/x648.html?product_id=884227&origin_id=x4325&InvalidQS=go.y=12&end_volume_number=8199&InvalidQS=go.x=8&InvalidQS=go.y=10&start_at=41&start_volume_number=8100) (ISBN:9780819487544)',
        'B. J. Patil, S. D. Dhole, Studies on (i) Characterization of Bremsstrahlung Spectra from High Z elements and (ii) Development of Neutron Source Using MeV Pulsed Electron Beam and Their Applications. Proc. of DAE Symposium on Nuclear Physics, Vol. 55, 828, (2010) (http://sympnp.org/proceedings/index.php)& also published online at Medical Physics Journal. http://www.medphys.org/PhdAbstracts/  .  ',

    ]
}


export { mubarak, bhushan, adinath };